// ============================================================================
// Données du jeu "Safari Planète" (même moteur que le mode Monuments de
// Pin the Globe).
//
// Chaque animal :
//  - name             : nom affiché
//  - kind             : sa classe (mammifère, oiseau, reptile…)
//  - country, flags   : où se trouve le point choisi (texte) et drapeaux
//  - continent        : sert à répartir les animaux d'une partie sur la Terre
//  - lat, lon         : un endroit typique de son milieu naturel
//  - habitat          : son milieu naturel (révélé après la réponse)
//  - icon, clue, stat, facts : comme pour les monuments
//  - photo, credit    : une vraie photo de l'animal, venant de Wikimedia Commons.
//                       Elle est libre de droits à condition de citer son
//                       auteur : "credit" est affiché sous la photo et sur la
//                       page credits.html (photoNote : légende éventuelle).
// ============================================================================

export const ANIMAL_KINDS = {
  mammifere: { label: 'Mammifère', icon: '🐾' },
  oiseau: { label: 'Oiseau', icon: '🐦' },
  reptile: { label: 'Reptile', icon: '🦎' },
  amphibien: { label: 'Amphibien', icon: '🐸' },
  poisson: { label: 'Poisson', icon: '🐟' },
  insecte: { label: 'Insecte', icon: '🦋' },
};

export const ANIMALS = [
  // ------------------------------------------------------------- Afrique
  {
    id: 'lion', name: 'Lion', kind: 'mammifere', country: 'Tanzanie (Serengeti)', flags: ['tz'], continent: 'Afrique',
    lat: -2.33, lon: 34.83, icon: '🦁', habitat: 'Savane',
    clue: 'Le « roi des animaux », qui vit en groupe dans la savane.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/011_The_lion_king_Tryggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/960px-011_The_lion_king_Tryggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg",
    credit: { author: "Giles Laurent", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:011_The_lion_king_Tryggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 250 kg" },
    facts: [
      'Les lions vivent en groupes appelés troupes : ce sont surtout les lionnes qui chassent.',
      "Le rugissement d'un lion s'entend jusqu'à 8 km !",
    ],
  },
  {
    id: 'elephant-afrique', name: "Éléphant d'Afrique", kind: 'mammifere', country: 'Kenya (Amboseli)', flags: ['ke'], continent: 'Afrique',
    lat: -2.65, lon: 37.26, icon: '🐘', habitat: 'Savane et forêts',
    clue: 'Le plus grand animal terrestre, avec une trompe et de très grandes oreilles.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/960px-African_Bush_Elephant.jpg",
    credit: { author: "Muhammad Mahdi Karim", license: "GFDL 1.2", page: "https://commons.wikimedia.org/wiki/File:African_Bush_Elephant.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 6 tonnes" },
    facts: [
      "Ses grandes oreilles l'aident à se rafraîchir, comme des éventails.",
      'Sa trompe contient des dizaines de milliers de muscles !',
    ],
  },
  {
    id: 'girafe', name: 'Girafe', kind: 'mammifere', country: 'Namibie (Etosha)', flags: ['na'], continent: 'Afrique',
    lat: -18.85, lon: 16.33, icon: '🦒', habitat: 'Savane arborée',
    clue: 'Le plus grand animal du monde… en hauteur !',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Giraffa_camelopardalis_angolensis.jpg/960px-Giraffa_camelopardalis_angolensis.jpg",
    credit: { author: "Hans Hillewaert", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Giraffa_camelopardalis_angolensis.jpg" },
    stat: { label: 'Taille', value: "jusqu'à 5,5 m" },
    facts: [
      'Malgré son long cou, elle a autant de vertèbres dans le cou que nous : sept !',
      'Sa langue, bleu-noir, mesure environ 50 cm.',
    ],
  },
  {
    id: 'zebre', name: 'Zèbre des plaines', kind: 'mammifere', country: 'Botswana', flags: ['bw'], continent: 'Afrique',
    lat: -20.5, lon: 25.0, icon: '🦓', habitat: 'Savane et prairies',
    clue: 'Un cheval sauvage rayé de noir et de blanc.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Equus_quagga_burchellii_-_Etosha%2C_2014.jpg/960px-Equus_quagga_burchellii_-_Etosha%2C_2014.jpg",
    credit: { author: "Yathin S Krishnappa", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Equus_quagga_burchellii_-_Etosha,_2014.jpg" },
    stat: { label: 'Vitesse', value: "jusqu'à 65 km/h" },
    facts: [
      'Chaque zèbre a des rayures uniques, comme nos empreintes digitales.',
      'Ses rayures pourraient servir à éloigner les mouches piqueuses.',
    ],
  },
  {
    id: 'hippopotame', name: 'Hippopotame', kind: 'mammifere', country: 'Zambie (South Luangwa)', flags: ['zm'], continent: 'Afrique',
    lat: -13.1, lon: 31.6, icon: '🦛', habitat: 'Rivières et lacs',
    clue: "Un énorme animal qui passe ses journées dans l'eau des rivières.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Hipop%C3%B3tamos_%28Hippopotamus_amphibius%29%2C_parque_nacional_de_Chobe%2C_Botsuana%2C_2018-07-28%2C_DD_81.jpg/960px-Hipop%C3%B3tamos_%28Hippopotamus_amphibius%29%2C_parque_nacional_de_Chobe%2C_Botsuana%2C_2018-07-28%2C_DD_81.jpg",
    credit: { author: "Diego Delso", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Hipop%C3%B3tamos_(Hippopotamus_amphibius),_parque_nacional_de_Chobe,_Botsuana,_2018-07-28,_DD_81.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 3 tonnes" },
    facts: [
      "Il ne sait pas vraiment nager : il marche ou rebondit au fond de l'eau !",
      'Sa peau produit une substance rougeâtre qui la protège du soleil.',
    ],
  },
  {
    id: 'gorille', name: 'Gorille des montagnes', kind: 'mammifere', country: 'Rwanda (volcans des Virunga)', flags: ['rw'], continent: 'Afrique',
    lat: -1.47, lon: 29.5, icon: '🦍', habitat: 'Forêts de montagne',
    clue: 'Le plus grand des singes, qui vit dans les forêts de montagnes volcaniques.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Mountain_gorilla_looking_%286461814405%29.jpg/960px-Mountain_gorilla_looking_%286461814405%29.jpg",
    credit: { author: "U.S. Fish and Wildlife Service", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Mountain_gorilla_looking_(6461814405).jpg" },
    stat: { label: 'Poids', value: "jusqu'à 200 kg" },
    facts: [
      'Le mâle chef de groupe est appelé « dos argenté », à cause des poils gris de son dos.',
      'Il est surtout végétarien : il mange des feuilles, des tiges et des fruits.',
    ],
  },
  {
    id: 'chimpanze', name: 'Chimpanzé', kind: 'mammifere', country: 'Tanzanie (Gombe)', flags: ['tz'], continent: 'Afrique',
    lat: -4.67, lon: 29.63, icon: '🐒', habitat: 'Forêts tropicales',
    clue: 'Un singe très intelligent qui sait utiliser des outils.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/015_Chimpanzee_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg/960px-015_Chimpanzee_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg",
    credit: { author: "Giles Laurent", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:015_Chimpanzee_at_Kibale_forest_National_Park_Photo_by_Giles_Laurent.jpg" },
    stat: { label: 'ADN en commun avec nous', value: 'environ 98 %' },
    facts: [
      'Il fabrique des outils, comme des brindilles pour « pêcher » les termites.',
      "La scientifique Jane Goodall l'a étudié pendant des dizaines d'années à Gombe, en Tanzanie.",
    ],
  },
  {
    id: 'guepard', name: 'Guépard', kind: 'mammifere', country: 'Kenya (Masai Mara)', flags: ['ke'], continent: 'Afrique',
    lat: -1.5, lon: 35.1, icon: '🐆', habitat: 'Savane',
    clue: "L'animal terrestre le plus rapide du monde.",
    photo: "https://upload.wikimedia.org/wikipedia/commons/0/09/TheCheethcat.jpg",
    credit: { author: "James Temple", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:TheCheethcat.jpg" },
    stat: { label: 'Vitesse', value: 'plus de 100 km/h' },
    facts: [
      'Il ne peut courir à toute vitesse que sur quelques centaines de mètres.',
      "Les traits noirs sous ses yeux, comme des larmes, l'aideraient à ne pas être ébloui par le soleil.",
    ],
  },
  {
    id: 'rhinoceros-blanc', name: 'Rhinocéros blanc', kind: 'mammifere', country: 'Afrique du Sud (parc Kruger)', flags: ['za'], continent: 'Afrique',
    lat: -24.0, lon: 31.5, icon: '🦏', habitat: 'Savane',
    clue: 'Un géant cuirassé qui porte deux cornes sur le nez.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Rhinoc%C3%A9ros_blanc_JHE.jpg/960px-Rhinoc%C3%A9ros_blanc_JHE.jpg",
    credit: { author: "Coralie", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Rhinoc%C3%A9ros_blanc_JHE.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 3,5 tonnes" },
    facts: [
      'Sa corne est faite de kératine, comme nos ongles et nos cheveux.',
      'Il est menacé par le braconnage, à cause de ses cornes.',
    ],
  },
  {
    id: 'maki-catta', name: 'Maki catta', kind: 'mammifere', country: 'Madagascar', flags: ['mg'], continent: 'Afrique',
    lat: -24.0, lon: 45.5, icon: '🐒', habitat: 'Forêts sèches',
    clue: 'Un petit primate à la queue rayée noir et blanc, qui vit sur une très grande île.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Lemur_catta_2018.jpg/960px-Lemur_catta_2018.jpg",
    credit: { author: "Architas", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Lemur_catta_2018.jpg" },
    stat: { label: 'Queue', value: 'environ 60 cm' },
    facts: [
      "Les lémuriens comme lui ne vivent à l'état sauvage qu'à Madagascar.",
      'Le matin, il se « bronze » au soleil, les bras écartés, pour se réchauffer.',
    ],
  },
  {
    id: 'okapi', name: 'Okapi', kind: 'mammifere', country: "République démocratique du Congo (forêt de l'Ituri)", flags: ['cd'], continent: 'Afrique',
    lat: 1.4, lon: 28.6, icon: '🦒', habitat: 'Forêt tropicale dense',
    clue: "Il a des rayures de zèbre sur les pattes, mais c'est un cousin de la girafe.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Okapi2.jpg/960px-Okapi2.jpg",
    credit: { author: "Raul654", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Okapi2.jpg" },
    stat: { label: 'Poids', value: '200 à 350 kg' },
    facts: [
      "Les scientifiques européens ne l'ont découvert qu'en 1901 !",
      'Il vit seulement dans les forêts de la République démocratique du Congo.',
    ],
  },
  {
    id: 'crocodile-nil', name: 'Crocodile du Nil', kind: 'reptile', country: 'Ouganda (chutes Murchison)', flags: ['ug'], continent: 'Afrique',
    lat: 2.28, lon: 31.6, icon: '🐊', habitat: 'Fleuves, lacs et marais',
    clue: 'Un grand reptile aux mâchoires puissantes qui guette ses proies dans les fleuves.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/NileCrocodile.jpg/960px-NileCrocodile.jpg",
    credit: { author: "Dewet", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:NileCrocodile.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 5 m" },
    facts: [
      "Il peut rester sous l'eau plus d'une heure sans respirer.",
      'La température du nid décide si les bébés seront des mâles ou des femelles !',
    ],
  },
  {
    id: 'flamant-nain', name: 'Flamant nain', kind: 'oiseau', country: 'Kenya (lac Nakuru)', flags: ['ke'], continent: 'Afrique',
    lat: -0.37, lon: 36.09, icon: '🦩', habitat: 'Lacs salés',
    clue: 'Un oiseau rose qui se tient souvent sur une seule patte.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Lesser_Flamingo_AMSM3035.jpg/960px-Lesser_Flamingo_AMSM3035.jpg",
    credit: { author: "Savithri Singh", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Lesser_Flamingo_AMSM3035.jpg" },
    stat: { label: 'Taille', value: 'environ 90 cm' },
    facts: [
      'Sa couleur rose vient des petites algues qu\'il mange.',
      "Il mange la tête à l'envers, en filtrant l'eau avec son bec.",
    ],
  },
  {
    id: 'suricate', name: 'Suricate', kind: 'mammifere', country: 'Désert du Kalahari (Afrique du Sud, Botswana)', flags: ['za', 'bw'], continent: 'Afrique',
    lat: -26.5, lon: 20.6, icon: '🐾', habitat: 'Désert et savane sèche',
    clue: 'Un petit mammifère qui monte la garde, debout sur ses pattes arrière.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Meerkat_%28Suricata_suricatta%29_Tswalu.jpg/960px-Meerkat_%28Suricata_suricatta%29_Tswalu.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Meerkat_(Suricata_suricatta)_Tswalu.jpg" },
    stat: { label: 'Taille', value: 'environ 30 cm' },
    facts: [
      'Pendant que le groupe cherche à manger, une sentinelle surveille et crie en cas de danger.',
      'Les suricates vivent en famille dans des terriers creusés dans le sable.',
    ],
  },
  {
    id: 'fennec', name: 'Fennec', kind: 'mammifere', country: 'Sahara (Algérie, Tunisie, Maroc…)', flags: ['dz', 'tn', 'ma'], continent: 'Afrique',
    lat: 26.5, lon: 4.0, icon: '🦊', habitat: 'Désert de sable',
    clue: "Le plus petit renard du monde, avec d'immenses oreilles.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Fennec_Fox_Vulpes_zerda.jpg/960px-Fennec_Fox_Vulpes_zerda.jpg",
    credit: { author: "Drew Avery", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Fennec_Fox_Vulpes_zerda.jpg" },
    stat: { label: 'Oreilles', value: "jusqu'à 15 cm" },
    facts: [
      "Ses grandes oreilles l'aident à se rafraîchir et à entendre les insectes sous le sable.",
      'Ses pattes poilues le protègent du sable brûlant.',
    ],
  },
  {
    id: 'autruche', name: 'Autruche', kind: 'oiseau', country: 'Kenya (Tsavo)', flags: ['ke'], continent: 'Afrique',
    lat: -3.0, lon: 38.5, icon: '🐦', habitat: 'Savane et zones sèches',
    clue: 'Le plus grand oiseau du monde : il ne vole pas, mais court très vite.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Struthio_camelus_-_Etosha_2014_%283%29.jpg/960px-Struthio_camelus_-_Etosha_2014_%283%29.jpg",
    credit: { author: "Yathin S Krishnappa", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Struthio_camelus_-_Etosha_2014_(3).jpg" },
    stat: { label: 'Œuf', value: 'environ 1,5 kg' },
    facts: [
      "Elle peut courir jusqu'à 70 km/h.",
      'Son œuf est le plus gros de tous les oiseaux : il équivaut à environ 24 œufs de poule !',
    ],
  },
  {
    id: 'mandrill', name: 'Mandrill', kind: 'mammifere', country: 'Gabon (parc de la Lopé)', flags: ['ga'], continent: 'Afrique',
    lat: -0.7, lon: 11.6, icon: '🐒', habitat: 'Forêt tropicale',
    clue: 'Le plus grand des singes à queue, au visage coloré de rouge et de bleu.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Mandril.jpg/500px-Mandril.jpg",
    credit: { author: "Malene Thyssen", license: "CC BY 2.5", page: "https://commons.wikimedia.org/wiki/File:Mandril.jpg" },
    stat: { label: 'Groupe', value: "jusqu'à plusieurs centaines" },
    facts: [
      'Plus son visage est coloré, plus le mâle impressionne les autres.',
      "Les mandrills vivent parfois en groupes de plusieurs centaines d'individus !",
    ],
  },
  {
    id: 'lycaon', name: 'Lycaon', kind: 'mammifere', country: 'Botswana (delta de l\'Okavango)', flags: ['bw'], continent: 'Afrique',
    lat: -19.2, lon: 22.9, icon: '🐕', habitat: 'Savane',
    clue: 'Un chien sauvage au pelage tacheté, qui chasse en meute.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/African_Wild_Dog_at_Working_with_Wildlife.jpg/960px-African_Wild_Dog_at_Working_with_Wildlife.jpg",
    credit: { author: "AfricanConservation", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:African_Wild_Dog_at_Working_with_Wildlife.jpg" },
    stat: { label: 'Vitesse', value: "jusqu'à 65 km/h" },
    facts: [
      'Chaque lycaon a un pelage unique, avec des taches de couleurs différentes.',
      "C'est l'un des chasseurs les plus efficaces : la plupart de ses chasses réussissent.",
    ],
  },
  {
    id: 'manchot-cap', name: 'Manchot du Cap', kind: 'oiseau', country: 'Afrique du Sud (plage de Boulders)', flags: ['za'], continent: 'Afrique',
    lat: -34.2, lon: 18.45, icon: '🐧', habitat: 'Plages et côtes',
    clue: "Un manchot qui vit sur les plages ensoleillées du sud de l'Afrique.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Manchot-du-cap-zoom.jpg/960px-Manchot-du-cap-zoom.jpg",
    credit: { author: "Pompomclai", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Manchot-du-cap-zoom.jpg" },
    stat: { label: 'Taille', value: 'environ 60 cm' },
    facts: [
      "Son cri ressemble à celui d'un âne : on l'appelait autrefois « manchot jackass ».",
      "Les taches roses au-dessus de ses yeux l'aident à évacuer la chaleur.",
    ],
  },
  {
    id: 'cameleon', name: 'Caméléon panthère', kind: 'reptile', country: 'Madagascar (Nosy Be)', flags: ['mg'], continent: 'Afrique',
    lat: -13.3, lon: 48.3, icon: '🦎', habitat: 'Forêts tropicales',
    clue: 'Un lézard qui change de couleur et dont les yeux bougent chacun de leur côté.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/4/49/Chamaeleon1a.jpg",
    credit: { author: "Auteur inconnu", license: "Copyrighted free use", page: "https://commons.wikimedia.org/wiki/File:Chamaeleon1a.jpg" },
    stat: { label: 'Langue', value: "jusqu'à 2 fois son corps" },
    facts: [
      'Ses deux yeux peuvent regarder dans deux directions différentes en même temps.',
      "Il change de couleur surtout pour communiquer et selon la température, pas seulement pour se cacher.",
    ],
  },

  // ------------------------------------------------------------- Asie
  {
    id: 'panda', name: 'Panda géant', kind: 'mammifere', country: 'Chine (montagnes du Sichuan)', flags: ['cn'], continent: 'Asie',
    lat: 30.8, lon: 103.3, icon: '🐼', habitat: 'Forêts de bambous en montagne',
    clue: 'Un ours noir et blanc qui mange presque uniquement du bambou.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Panda_at_the_Chengdu_Research_Base_of_Giant_Panda_Breeding%2C_Chengdu%2C_China_-_panoramio.jpg/960px-Panda_at_the_Chengdu_Research_Base_of_Giant_Panda_Breeding%2C_Chengdu%2C_China_-_panoramio.jpg",
    credit: { author: "Colin W", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Panda_at_the_Chengdu_Research_Base_of_Giant_Panda_Breeding,_Chengdu,_China_-_panoramio.jpg" },
    stat: { label: 'Bambou par jour', value: "jusqu'à 38 kg" },
    facts: [
      'Il passe environ 12 heures par jour à manger !',
      'À la naissance, le bébé panda est minuscule : il pèse environ 100 grammes.',
    ],
  },
  {
    id: 'tigre-bengale', name: 'Tigre du Bengale', kind: 'mammifere', country: 'Inde (parc de Kanha)', flags: ['in'], continent: 'Asie',
    lat: 22.3, lon: 80.6, icon: '🐯', habitat: 'Forêts et prairies',
    clue: 'Un grand félin au pelage orange rayé de noir.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Panthera_tigris_tigris.jpg/960px-Panthera_tigris_tigris.jpg",
    credit: { author: "John et Karen Hollingsworth (retouches : Zwoenitzer)", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Panthera_tigris_tigris.jpg" },
    stat: { label: 'Poids', value: 'plus de 200 kg' },
    facts: [
      "Contrairement à beaucoup de chats, il adore l'eau et nage très bien.",
      'Chaque tigre a des rayures différentes… même sur la peau, sous les poils !',
    ],
  },
  {
    id: 'orang-outan', name: 'Orang-outan', kind: 'mammifere', country: 'Indonésie (île de Bornéo)', flags: ['id', 'my'], continent: 'Asie',
    lat: -2.9, lon: 111.9, icon: '🦧', habitat: 'Forêt tropicale humide',
    clue: 'Un grand singe roux qui vit presque toujours dans les arbres.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Pongo_pygmaeus_%28orangutang%29.jpg/500px-Pongo_pygmaeus_%28orangutang%29.jpg",
    credit: { author: "Malene Thyssen", license: "CC BY 2.5", page: "https://commons.wikimedia.org/wiki/File:Pongo_pygmaeus_(orangutang).jpg" },
    stat: { label: 'Envergure des bras', value: "jusqu'à 2 m" },
    facts: [
      'Son nom vient du malais et signifie « homme de la forêt ».',
      'Chaque soir, il se construit un nouveau nid de branches pour dormir.',
    ],
  },
  {
    id: 'panda-roux', name: 'Panda roux', kind: 'mammifere', country: 'Himalaya (Népal, Inde, Bhoutan, Chine)', flags: ['np', 'bt'], continent: 'Asie',
    lat: 27.4, lon: 88.2, icon: '🦊', habitat: 'Forêts de montagne',
    clue: "Un petit mammifère roux à la queue annelée, qui vit dans les forêts de l'Himalaya.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Ailurus_mosaic.jpg/960px-Ailurus_mosaic.jpg",
    credit: { author: "Auteur inconnu", license: "CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:Ailurus_mosaic.jpg" },
    stat: { label: 'Poids', value: '3 à 6 kg' },
    facts: [
      'Il a été appelé « panda » bien avant le panda géant !',
      'Pour dormir au froid, il enroule sa longue queue autour de lui comme une couverture.',
    ],
  },
  {
    id: 'panthere-neiges', name: 'Panthère des neiges', kind: 'mammifere', country: 'Himalaya (Ladakh, Inde)', flags: ['in'], continent: 'Asie',
    lat: 34.1, lon: 77.6, icon: '🐆', habitat: 'Hautes montagnes',
    clue: 'Un félin au pelage épais et tacheté, qui vit dans les hautes montagnes enneigées.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/71/Uncia_uncia_-_A_tail_and_a_cat_cropped.jpg/960px-Uncia_uncia_-_A_tail_and_a_cat_cropped.jpg",
    credit: { author: "Marit & Toomas Hinnosaar", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Uncia_uncia_-_A_tail_and_a_cat_cropped.jpg" },
    stat: { label: 'Queue', value: 'presque 1 m' },
    facts: [
      "Sa longue queue lui sert d'écharpe et l'aide à garder l'équilibre dans les rochers.",
      'Elle peut faire des bonds de plusieurs mètres de long.',
    ],
  },
  {
    id: 'dragon-komodo', name: 'Dragon de Komodo', kind: 'reptile', country: 'Indonésie (île de Komodo)', flags: ['id'], continent: 'Asie',
    lat: -8.55, lon: 119.45, icon: '🦎', habitat: 'Îles sèches et savanes',
    clue: 'Le plus grand lézard du monde, qui ne vit que sur quelques îles.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Varanus_komodoensis1.jpg/960px-Varanus_komodoensis1.jpg",
    credit: { author: "Auteur inconnu", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Varanus_komodoensis1.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 3 m" },
    facts: [
      'Sa morsure est venimeuse.',
      'Il sent ses proies grâce à sa langue fourchue, parfois à plusieurs kilomètres.',
    ],
  },
  {
    id: 'elephant-asie', name: "Éléphant d'Asie", kind: 'mammifere', country: 'Sri Lanka (parc de Minneriya)', flags: ['lk'], continent: 'Asie',
    lat: 8.0, lon: 80.85, icon: '🐘', habitat: 'Forêts et prairies',
    clue: "Un éléphant aux oreilles plus petites que celles de son cousin d'Afrique.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Asian_elephant_-_melbourne_zoo.jpg/960px-Asian_elephant_-_melbourne_zoo.jpg",
    credit: { author: "Fir0002", license: "GFDL 1.2", page: "https://commons.wikimedia.org/wiki/File:Asian_elephant_-_melbourne_zoo.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 5 tonnes" },
    facts: [
      "Ses oreilles sont plus petites que celles de l'éléphant d'Afrique, et son dos est bombé.",
      "Il peut boire jusqu'à 200 litres d'eau par jour.",
    ],
  },
  {
    id: 'cobra-royal', name: 'Cobra royal', kind: 'reptile', country: 'Thaïlande (parc de Khao Yai)', flags: ['th'], continent: 'Asie',
    lat: 14.4, lon: 101.4, icon: '🐍', habitat: 'Forêts tropicales',
    clue: 'Le plus long serpent venimeux du monde.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/12_-_The_Mystical_King_Cobra_and_Coffee_Forests.jpg/960px-12_-_The_Mystical_King_Cobra_and_Coffee_Forests.jpg",
    credit: { author: "Michael Allen Smith from Seattle, USA", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:12_-_The_Mystical_King_Cobra_and_Coffee_Forests.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 5,5 m" },
    facts: [
      'Quand il se sent menacé, il redresse le haut de son corps et peut regarder un adulte dans les yeux.',
      "Il se nourrit surtout… d'autres serpents !",
    ],
  },
  {
    id: 'chameau-bactriane', name: 'Chameau de Bactriane', kind: 'mammifere', country: 'Mongolie et Chine (désert de Gobi)', flags: ['mn', 'cn'], continent: 'Asie',
    lat: 43.5, lon: 97.0, icon: '🐫', habitat: 'Désert froid',
    clue: 'Un chameau à deux bosses qui supporte aussi bien le froid que la chaleur.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Camel_seitlich_trabend.jpg/960px-Camel_seitlich_trabend.jpg",
    credit: { author: "BS Thurner Hof", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Camel_seitlich_trabend.jpg" },
    stat: { label: 'Bosses', value: '2' },
    facts: [
      "Ses bosses ne contiennent pas d'eau, mais de la graisse : une réserve d'énergie.",
      "Il peut boire plus de 100 litres d'eau en quelques minutes !",
    ],
  },
  {
    id: 'grue-japon', name: 'Grue du Japon', kind: 'oiseau', country: 'Japon (Hokkaido)', flags: ['jp'], continent: 'Asie',
    lat: 43.2, lon: 144.4, icon: '🐦', habitat: 'Marais',
    clue: 'Un grand oiseau blanc à tête rouge, symbole de longue vie, qui danse en hiver.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/eb/Mandschurenkranich_716.JPG/960px-Mandschurenkranich_716.JPG",
    credit: { author: "BS Thurner Hof", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Mandschurenkranich_716.JPG" },
    stat: { label: 'Envergure', value: "jusqu'à 2,5 m" },
    facts: [
      'Les couples dansent ensemble en sautant et en battant des ailes.',
      "Au Japon, elle est le symbole du bonheur et d'une longue vie.",
    ],
  },
  {
    id: 'macaque-japonais', name: 'Macaque japonais', kind: 'mammifere', country: 'Japon (Nagano)', flags: ['jp'], continent: 'Asie',
    lat: 36.73, lon: 138.46, icon: '🐒', habitat: 'Forêts de montagne enneigées',
    clue: 'Un singe qui se réchauffe dans les sources chaudes en hiver.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Wildlife_primate_macaca-fuscata_family.jpg/960px-Wildlife_primate_macaca-fuscata_family.jpg",
    credit: { author: "Alfonsopazphoto", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Wildlife_primate_macaca-fuscata_family.jpg" },
    stat: { label: 'Froid supporté', value: "jusqu'à −20 °C" },
    facts: [
      "C'est le singe qui vit le plus au nord du monde (en dehors des humains) !",
      'Certains prennent des bains dans les sources chaudes pour se réchauffer.',
    ],
  },
  {
    id: 'tigre-siberie', name: 'Tigre de Sibérie', kind: 'mammifere', country: 'Russie (Extrême-Orient)', flags: ['ru'], continent: 'Asie',
    lat: 45.5, lon: 135.5, icon: '🐅', habitat: 'Forêts froides',
    clue: 'Le plus grand tigre du monde, qui vit dans les forêts enneigées.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Tygr_ussurijsk%C3%BD_%28Panthera_tigris_altaica%29.jpg/960px-Tygr_ussurijsk%C3%BD_%28Panthera_tigris_altaica%29.jpg",
    credit: { author: "Zoo Hluboka", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Tygr_ussurijsk%C3%BD_(Panthera_tigris_altaica).jpg" },
    stat: { label: 'Poids', value: "jusqu'à 300 kg" },
    facts: [
      "On l'appelle aussi tigre de l'Amour, du nom d'un grand fleuve.",
      'Sa fourrure épaisse et une couche de graisse le protègent du froid.',
    ],
  },
  {
    id: 'paon', name: 'Paon bleu', kind: 'oiseau', country: 'Inde (parc de Ranthambore)', flags: ['in'], continent: 'Asie',
    lat: 26.0, lon: 76.5, icon: '🦚', habitat: 'Forêts claires et campagnes',
    clue: 'Un oiseau qui fait la roue avec une magnifique traîne couverte d\'« yeux ».',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/023_Indian_peafowl_in_Jim_Corbett_National_Park_Photo_by_Giles_Laurent.jpg/960px-023_Indian_peafowl_in_Jim_Corbett_National_Park_Photo_by_Giles_Laurent.jpg",
    credit: { author: "Giles Laurent", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:023_Indian_peafowl_in_Jim_Corbett_National_Park_Photo_by_Giles_Laurent.jpg" },
    stat: { label: 'Traîne', value: "jusqu'à 1,5 m" },
    facts: [
      'Seul le mâle porte la grande traîne colorée.',
      "C'est l'oiseau national de l'Inde.",
    ],
  },
  {
    id: 'tarsier', name: 'Tarsier des Philippines', kind: 'mammifere', country: 'Philippines (île de Bohol)', flags: ['ph'], continent: 'Asie',
    lat: 9.75, lon: 124.0, icon: '🐾', habitat: 'Forêts tropicales',
    clue: 'Un minuscule primate aux yeux énormes, actif la nuit.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Philippine_tarsier_%28Carlito_syrichta_fraterculus%29_Bohol_2.jpg/960px-Philippine_tarsier_%28Carlito_syrichta_fraterculus%29_Bohol_2.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Philippine_tarsier_(Carlito_syrichta_fraterculus)_Bohol_2.jpg" },
    stat: { label: 'Taille', value: 'environ 12 cm' },
    facts: [
      'Chacun de ses yeux est aussi gros que son cerveau !',
      'Il peut tourner la tête presque à 180°, comme un hibou.',
    ],
  },
  {
    id: 'yack', name: 'Yack sauvage', kind: 'mammifere', country: 'Chine (plateau du Tibet)', flags: ['cn'], continent: 'Asie',
    lat: 34.5, lon: 89.0, icon: '🐂', habitat: 'Hauts plateaux froids',
    clue: 'Un bovin à longs poils qui vit sur le « toit du monde ».',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Bos_grunniens_at_Yundrok_Yumtso_Lake.jpg/960px-Bos_grunniens_at_Yundrok_Yumtso_Lake.jpg",
    credit: { author: "Dennis G. Jarvis", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Bos_grunniens_at_Yundrok_Yumtso_Lake.jpg" },
    stat: { label: 'Altitude', value: 'plus de 5 000 m' },
    facts: [
      'Sa fourrure très épaisse le protège de températures de −40 °C.',
      'Les yacks domestiques sont précieux pour les habitants du Tibet : lait, laine, transport…',
    ],
  },
  {
    id: 'salamandre-geante', name: 'Salamandre géante de Chine', kind: 'amphibien', country: 'Chine (Hunan)', flags: ['cn'], continent: 'Asie',
    lat: 29.0, lon: 110.5, icon: '🦎', habitat: 'Rivières fraîches de montagne',
    clue: 'Le plus grand amphibien du monde, qui vit dans les rivières de montagne.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/Velemlok_%C4%8D%C3%ADnsk%C3%BD_zoo_praha_1.jpg/960px-Velemlok_%C4%8D%C3%ADnsk%C3%BD_zoo_praha_1.jpg",
    credit: { author: "Petr Hamerník", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Velemlok_%C4%8D%C3%ADnsk%C3%BD_zoo_praha_1.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 1,8 m" },
    facts: [
      'Elle respire en partie à travers sa peau.',
      'Elle peut vivre plus de 50 ans.',
    ],
  },
  {
    id: 'gavial', name: 'Gavial du Gange', kind: 'reptile', country: 'Inde (rivière Chambal)', flags: ['in', 'np'], continent: 'Asie',
    lat: 26.7, lon: 78.5, icon: '🐊', habitat: 'Grandes rivières',
    clue: 'Un crocodile au museau très long et très fin, qui pêche dans les rivières.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Indian_Gharial_Crocodile_Digon3.JPG/960px-Indian_Gharial_Crocodile_Digon3.JPG",
    credit: { author: "“Jonathan Zander (Digon3)”", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Indian_Gharial_Crocodile_Digon3.JPG" },
    stat: { label: 'Longueur', value: "jusqu'à 6 m" },
    facts: [
      'Son museau fin et ses nombreuses dents sont parfaits pour attraper les poissons.',
      "Le mâle a une bosse au bout du museau, qui ressemble à un pot appelé « ghara » en Inde.",
    ],
  },
  {
    id: 'tapir-malaisie', name: 'Tapir de Malaisie', kind: 'mammifere', country: 'Malaisie (Taman Negara)', flags: ['my', 'th'], continent: 'Asie',
    lat: 4.6, lon: 102.4, icon: '🐾', habitat: 'Forêt tropicale',
    clue: "Un mammifère noir et blanc à petite trompe, qui vit dans la jungle d'Asie.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Schabrackentapir_Tapirus_indicus_Tierpark_Hellabrunn-1.jpg/960px-Schabrackentapir_Tapirus_indicus_Tierpark_Hellabrunn-1.jpg",
    credit: { author: "Rufus46", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Schabrackentapir_Tapirus_indicus_Tierpark_Hellabrunn-1.jpg" },
    stat: { label: 'Poids', value: 'environ 300 kg' },
    facts: [
      'Son pelage noir et blanc le camoufle la nuit, au clair de lune.',
      'Les bébés tapirs sont bruns, avec des taches et des rayures blanches, comme des pastèques !',
    ],
  },
  {
    id: 'saiga', name: 'Saïga', kind: 'mammifere', country: 'Kazakhstan (steppes)', flags: ['kz'], continent: 'Asie',
    lat: 46.5, lon: 66.0, icon: '🐐', habitat: 'Steppes',
    clue: "Une antilope des steppes au drôle de nez en forme de petite trompe.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Saiga_tartarica.jpg/960px-Saiga_tartarica.jpg",
    credit: { author: "Navinder Singh", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Saiga_tartarica.jpg" },
    stat: { label: 'Poids', value: '25 à 50 kg' },
    facts: [
      "Son nez gonflé filtre la poussière l'été et réchauffe l'air glacé l'hiver.",
      'Les saïgas migrent en grands troupeaux à travers les steppes.',
    ],
  },
  {
    id: 'lion-asie', name: "Lion d'Asie", kind: 'mammifere', country: 'Inde (forêt de Gir)', flags: ['in'], continent: 'Asie',
    lat: 21.1, lon: 70.8, icon: '🦁', habitat: 'Forêts sèches',
    clue: "Un lion qui ne vit plus que dans une seule forêt d'Asie.",
    photo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Asiatic_Lioness_in_Gir_Forest.jpg",
    credit: { author: "Sumeet Moghe", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Asiatic_Lioness_in_Gir_Forest.jpg" },
    stat: { label: 'Population', value: 'quelques centaines' },
    facts: [
      "Il ne reste qu'une seule population sauvage, dans la forêt de Gir, en Inde.",
      "Le mâle a une crinière plus courte que le lion d'Afrique, qui laisse voir ses oreilles.",
    ],
  },
  {
    id: 'przewalski', name: 'Cheval de Przewalski', kind: 'mammifere', country: 'Mongolie (parc de Hustai)', flags: ['mn'], continent: 'Asie',
    lat: 47.8, lon: 105.9, icon: '🐎', habitat: 'Steppes',
    clue: 'Le dernier cheval vraiment sauvage du monde.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Przewalskis_horse_02.jpg",
    credit: { author: "Claudia Feh", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Przewalskis_horse_02.jpg" },
    stat: { label: 'Taille au garrot', value: 'environ 1,3 m' },
    facts: [
      "Il avait disparu à l'état sauvage, puis a été réintroduit en Mongolie dans les années 1990 grâce à des zoos.",
      'Il a une crinière droite et courte, comme une brosse.',
    ],
  },
  {
    id: 'rhinoceros-indien', name: 'Rhinocéros indien', kind: 'mammifere', country: 'Inde (parc de Kaziranga)', flags: ['in'], continent: 'Asie',
    lat: 26.6, lon: 93.3, icon: '🦏', habitat: 'Prairies humides',
    clue: 'Un rhinocéros à une seule corne, à la peau plissée comme une armure.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b7/One_horn_Rhino_in_Kaziranga_national_park.jpg/960px-One_horn_Rhino_in_Kaziranga_national_park.jpg",
    credit: { author: "Anuwar ali hazarika", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:One_horn_Rhino_in_Kaziranga_national_park.jpg" },
    stat: { label: 'Cornes', value: '1' },
    facts: [
      'Sa peau forme de grands plis qui ressemblent à une armure.',
      'Le parc de Kaziranga, en Inde, abrite environ les deux tiers de tous les rhinocéros indiens.',
    ],
  },

  // ------------------------------------------------------------- Europe
  {
    id: 'ours-brun', name: 'Ours brun', kind: 'mammifere', country: 'Roumanie (Carpates)', flags: ['ro'], continent: 'Europe',
    lat: 45.5, lon: 25.3, icon: '🐻', habitat: 'Forêts de montagne',
    clue: "Un grand ours des forêts d'Europe qui dort une bonne partie de l'hiver.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ca/Niedzwied%C5%BA_brunatny_02_%28cropped%29.jpg/960px-Niedzwied%C5%BA_brunatny_02_%28cropped%29.jpg",
    credit: { author: "Aneta p", license: "CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:Niedzwied%C5%BA_brunatny_02_(cropped).jpg" },
    stat: { label: 'Poids', value: "jusqu'à 300 kg" },
    facts: [
      "En hiver, il hiberne dans une tanière : il peut ne pas manger pendant des mois.",
      'Il mange de tout : baies, racines, miel, poissons…',
    ],
  },
  {
    id: 'loup', name: 'Loup gris', kind: 'mammifere', country: 'Italie (Abruzzes)', flags: ['it'], continent: 'Europe',
    lat: 41.8, lon: 13.8, icon: '🐺', habitat: 'Forêts et montagnes',
    clue: "L'ancêtre sauvage du chien, qui vit et chasse en meute.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Eurasian_wolf_2.jpg/960px-Eurasian_wolf_2.jpg",
    credit: { author: "Mas3cf", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Eurasian_wolf_2.jpg" },
    stat: { label: 'Meute', value: 'souvent 4 à 8 loups' },
    facts: [
      "Le hurlement des loups s'entend à plusieurs kilomètres.",
      'Tous les chiens descendent du loup !',
    ],
  },
  {
    id: 'renne', name: 'Renne', kind: 'mammifere', country: 'Laponie (Norvège, Suède, Finlande)', flags: ['no', 'se', 'fi'], continent: 'Europe',
    lat: 68.5, lon: 25.0, icon: '🦌', habitat: 'Toundra',
    clue: 'Un cerf du Grand Nord dont les mâles ET les femelles portent des bois.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/20070818-0001-strolling_reindeer.jpg/960px-20070818-0001-strolling_reindeer.jpg",
    credit: { author: "Alexandre Buisse (Nattfodd)", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:20070818-0001-strolling_reindeer.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 180 kg" },
    facts: [
      "C'est le seul cerf dont les femelles ont aussi des bois.",
      "Ses sabots larges l'empêchent de s'enfoncer dans la neige, comme des raquettes.",
    ],
  },
  {
    id: 'macareux', name: 'Macareux moine', kind: 'oiseau', country: 'Islande (îles Vestmann)', flags: ['is'], continent: 'Europe',
    lat: 63.4, lon: -20.3, icon: '🐦', habitat: 'Falaises au bord de la mer',
    clue: 'Un petit oiseau marin au bec orange coloré, surnommé « perroquet des mers ».',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Papageitaucher_Fratercula_arctica_02.jpg/960px-Papageitaucher_Fratercula_arctica_02.jpg",
    credit: { author: "Richard Bartz", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Papageitaucher_Fratercula_arctica_02.jpg" },
    stat: { label: 'Taille', value: 'environ 30 cm' },
    facts: [
      'Il peut porter plus de 10 petits poissons à la fois dans son bec !',
      "Il bat des ailes jusqu'à 400 fois par minute.",
    ],
  },
  {
    id: 'lynx-iberique', name: 'Lynx ibérique', kind: 'mammifere', country: 'Espagne (Andalousie)', flags: ['es'], continent: 'Europe',
    lat: 37.1, lon: -6.4, icon: '🐈', habitat: 'Maquis et forêts méditerranéennes',
    clue: 'Un félin aux oreilles terminées par des pinceaux de poils noirs.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Lince_ib%C3%A9rico_%28Lynx_pardinus%29%2C_Almuradiel%2C_Ciudad_Real%2C_Espa%C3%B1a%2C_2021-12-19%2C_DD_02.jpg/960px-Lince_ib%C3%A9rico_%28Lynx_pardinus%29%2C_Almuradiel%2C_Ciudad_Real%2C_Espa%C3%B1a%2C_2021-12-19%2C_DD_02.jpg",
    credit: { author: "Diego Delso", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Lince_ib%C3%A9rico_(Lynx_pardinus),_Almuradiel,_Ciudad_Real,_Espa%C3%B1a,_2021-12-19,_DD_02.jpg" },
    stat: { label: 'Poids', value: 'environ 10 kg' },
    facts: [
      "Il a failli disparaître : en 2002, il n'en restait qu'une centaine.",
      'Il se nourrit presque uniquement de lapins.',
    ],
  },
  {
    id: 'bouquetin', name: 'Bouquetin des Alpes', kind: 'mammifere', country: 'Alpes (Italie, France, Suisse)', flags: ['it', 'fr', 'ch'], continent: 'Europe',
    lat: 45.5, lon: 7.25, icon: '🐐', habitat: 'Haute montagne',
    clue: 'Une chèvre sauvage aux grandes cornes, qui escalade les falaises.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/003_Wild_Alpine_Ibex_Sunset_Creux_du_Van_Mont_Racine_Photo_by_Giles_Laurent.jpg/960px-003_Wild_Alpine_Ibex_Sunset_Creux_du_Van_Mont_Racine_Photo_by_Giles_Laurent.jpg",
    credit: { author: "Giles Laurent", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:003_Wild_Alpine_Ibex_Sunset_Creux_du_Van_Mont_Racine_Photo_by_Giles_Laurent.jpg" },
    stat: { label: 'Cornes', value: "jusqu'à 1 m" },
    facts: [
      'Il grimpe sur des parois presque verticales grâce à ses sabots très adhérents.',
      "Il avait presque disparu au XIXᵉ siècle : il a été sauvé dans le parc du Grand-Paradis, en Italie.",
    ],
  },
  {
    id: 'bison-europe', name: "Bison d'Europe", kind: 'mammifere', country: 'Pologne et Biélorussie (forêt de Białowieża)', flags: ['pl', 'by'], continent: 'Europe',
    lat: 52.7, lon: 23.9, icon: '🐂', habitat: 'Forêts',
    clue: "Le plus lourd animal terrestre d'Europe.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/European_Bison.JPG/960px-European_Bison.JPG",
    credit: { author: "Talks Presenters 09 (talk)", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:European_Bison.JPG" },
    stat: { label: 'Poids', value: "jusqu'à 900 kg" },
    facts: [
      "Il avait complètement disparu à l'état sauvage en 1927, puis a été réintroduit grâce à des animaux de zoo.",
      'La forêt de Białowieża est son royaume.',
    ],
  },
  {
    id: 'orque', name: 'Orque', kind: 'mammifere', country: 'Norvège (fjords près de Tromsø)', flags: ['no'], continent: 'Europe',
    lat: 69.8, lon: 18.5, icon: '🐋', habitat: 'Océans, surtout les eaux froides',
    clue: 'Un grand dauphin noir et blanc, super-prédateur des océans.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Killerwhales_jumping.jpg/960px-Killerwhales_jumping.jpg",
    credit: { author: "Robert Pittman", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Killerwhales_jumping.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 9 m" },
    facts: [
      "Malgré son surnom de « baleine tueuse », c'est le plus grand des dauphins.",
      'Les orques chassent en groupe, avec des techniques transmises de génération en génération.',
    ],
  },
  {
    id: 'morse', name: 'Morse', kind: 'mammifere', country: 'Norvège (archipel du Svalbard)', flags: ['no'], continent: 'Europe',
    lat: 78.5, lon: 16.0, icon: '🦷', habitat: 'Banquise et côtes arctiques',
    clue: 'Un gros mammifère marin moustachu aux longues défenses.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/3/35/7_Walross_1999.jpg",
    credit: { author: "Ansgar Walk", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:7_Walross_1999.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 1,5 tonne" },
    facts: [
      'Il utilise ses défenses pour se hisser sur la glace.',
      "Ses moustaches très sensibles l'aident à trouver les coquillages au fond de la mer.",
    ],
  },
  {
    id: 'cigogne', name: 'Cigogne blanche', kind: 'oiseau', country: 'France (Alsace)', flags: ['fr'], continent: 'Europe',
    lat: 48.1, lon: 7.4, icon: '🐦', habitat: 'Prairies humides et villages',
    clue: 'Un grand oiseau blanc et noir qui fait son nid sur les toits et les clochers.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Stork_%28Palic%2C_Serbia%29.jpg/960px-Stork_%28Palic%2C_Serbia%29.jpg",
    credit: { author: "Dcabrilo", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Stork_(Palic,_Serbia).jpg" },
    stat: { label: 'Envergure', value: "jusqu'à 2 m" },
    facts: [
      "C'est le symbole de l'Alsace.",
      "À l'automne, la plupart des cigognes s'envolent pour passer l'hiver en Afrique.",
    ],
  },
  {
    id: 'marmotte', name: 'Marmotte des Alpes', kind: 'mammifere', country: 'Suisse (Alpes)', flags: ['ch'], continent: 'Europe',
    lat: 46.6, lon: 9.9, icon: '🐿️', habitat: 'Prairies de montagne',
    clue: 'Un rongeur des montagnes qui siffle pour prévenir du danger.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/071_Wild_marmot_at_Grand_Muveran_Nature_Reserve_Photo_by_Giles_Laurent.jpg/960px-071_Wild_marmot_at_Grand_Muveran_Nature_Reserve_Photo_by_Giles_Laurent.jpg",
    credit: { author: "Photography captured by Giles Laurent", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:071_Wild_marmot_at_Grand_Muveran_Nature_Reserve_Photo_by_Giles_Laurent.jpg" },
    stat: { label: 'Hibernation', value: "jusqu'à 6 mois" },
    facts: [
      "Elle siffle très fort pour prévenir les autres quand un aigle approche.",
      'Elle hiberne en famille dans un terrier, serrée contre les autres.',
    ],
  },

  // ------------------------------------------------------------- Amérique du Nord
  {
    id: 'bison-amerique', name: "Bison d'Amérique", kind: 'mammifere', country: 'États-Unis (Yellowstone)', flags: ['us'], continent: 'Amérique du Nord',
    lat: 44.6, lon: -110.5, icon: '🐂', habitat: 'Prairies',
    clue: 'Un énorme bovin à bosse qui vivait par millions dans les grandes plaines.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Bison_bison_009.jpg/960px-Bison_bison_009.jpg",
    credit: { author: "Donnie from WV, USA", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Bison_bison_009.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 1 tonne" },
    facts: [
      "Il y a 200 ans, des dizaines de millions de bisons parcouraient l'Amérique du Nord.",
      "Malgré sa taille, il peut courir à 55 km/h.",
    ],
  },
  {
    id: 'grizzly', name: 'Grizzly', kind: 'mammifere', country: 'États-Unis (Alaska, parc de Katmai)', flags: ['us'], continent: 'Amérique du Nord',
    lat: 58.5, lon: -155.0, icon: '🐻', habitat: 'Forêts et rivières du Nord',
    clue: 'Un grand ours brun qui pêche les saumons dans les rivières.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a9/GrizzlyBearJeanBeaufort.jpg/960px-GrizzlyBearJeanBeaufort.jpg",
    credit: { author: "Jean Beaufort", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:GrizzlyBearJeanBeaufort.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 400 kg" },
    facts: [
      "Il attrape les saumons qui sautent dans les chutes d'eau.",
      "Avant l'hiver, il mange énormément pour faire des réserves de graisse.",
    ],
  },
  {
    id: 'pygargue', name: 'Pygargue à tête blanche', kind: 'oiseau', country: 'Canada (île de Vancouver)', flags: ['ca', 'us'], continent: 'Amérique du Nord',
    lat: 50.0, lon: -125.5, icon: '🦅', habitat: 'Bords de lacs, de rivières et de mer',
    clue: "Un grand aigle à tête blanche, symbole d'un grand pays.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Bald_Eagle_%28Haliaeetus_leucocephalus%29_Kachemak_Bay%2C_Alaska.jpg/960px-Bald_Eagle_%28Haliaeetus_leucocephalus%29_Kachemak_Bay%2C_Alaska.jpg",
    credit: { author: "Andy Morffew from Itchen Abbas, Hampshire, UK", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Bald_Eagle_(Haliaeetus_leucocephalus)_Kachemak_Bay,_Alaska.jpg" },
    stat: { label: 'Envergure', value: "jusqu'à 2,3 m" },
    facts: [
      "C'est l'emblème national des États-Unis.",
      "Son nid peut peser plus d'une tonne !",
    ],
  },
  {
    id: 'raton-laveur', name: 'Raton laveur', kind: 'mammifere', country: 'États-Unis (Appalaches)', flags: ['us', 'ca'], continent: 'Amérique du Nord',
    lat: 37.5, lon: -79.5, icon: '🦝', habitat: "Forêts près de l'eau",
    clue: 'Un petit mammifère masqué qui semble « laver » sa nourriture.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3e/Raccoon_in_Central_Park_%2835264%29.jpg/960px-Raccoon_in_Central_Park_%2835264%29.jpg",
    credit: { author: "Rhododendrites", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Raccoon_in_Central_Park_(35264).jpg" },
    stat: { label: 'Poids', value: '4 à 9 kg' },
    facts: [
      "Il trempe souvent sa nourriture dans l'eau pour mieux la sentir avec ses pattes.",
      'Ses pattes avant sont très agiles : il sait ouvrir des boîtes !',
    ],
  },
  {
    id: 'orignal', name: 'Orignal (élan)', kind: 'mammifere', country: 'Canada (Québec)', flags: ['ca'], continent: 'Amérique du Nord',
    lat: 48.5, lon: -72.0, icon: '🦌', habitat: 'Forêts boréales et marais',
    clue: 'Le plus grand des cerfs, avec d\'immenses bois plats.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Alaska_moose.jpg/960px-Alaska_moose.jpg",
    credit: { author: "Paxson Woelber", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Alaska_moose.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 700 kg" },
    facts: [
      'Au Canada, on l\'appelle orignal ; en Europe, élan.',
      'Excellent nageur, il peut plonger pour manger des plantes aquatiques.',
    ],
  },
  {
    id: 'alligator', name: "Alligator d'Amérique", kind: 'reptile', country: 'États-Unis (Everglades, Floride)', flags: ['us'], continent: 'Amérique du Nord',
    lat: 25.4, lon: -80.9, icon: '🐊', habitat: 'Marais',
    clue: 'Un grand reptile des marais, au museau large et arrondi.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/American_Alligator.jpg/960px-American_Alligator.jpg",
    credit: { author: "Postdlf", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:American_Alligator.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 4,5 m" },
    facts: [
      'On le distingue du crocodile grâce à son museau plus large, en forme de U.',
      "Il a environ 80 dents, qui repoussent quand elles tombent.",
    ],
  },
  {
    id: 'axolotl', name: 'Axolotl', kind: 'amphibien', country: 'Mexique (canaux de Xochimilco)', flags: ['mx'], continent: 'Amérique du Nord',
    lat: 19.27, lon: -99.1, icon: '🦎', habitat: 'Lacs et canaux',
    clue: "Un amphibien qui garde toute sa vie l'allure d'un têtard, avec des branchies en plumeau.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Ambystoma_mexicanum_-_Aksolotli%2C_Mexican_axolotl_C_IMG_3700.JPG/960px-Ambystoma_mexicanum_-_Aksolotli%2C_Mexican_axolotl_C_IMG_3700.JPG",
    credit: { author: "Anneli Salo", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Ambystoma_mexicanum_-_Aksolotli,_Mexican_axolotl_C_IMG_3700.JPG" },
    stat: { label: 'Taille', value: 'environ 25 cm' },
    facts: [
      'Il peut faire repousser une patte, sa queue et même une partie de son cœur !',
      "À l'état sauvage, il ne vit que dans les canaux de Xochimilco, près de Mexico.",
    ],
  },
  {
    id: 'monarque', name: 'Papillon monarque', kind: 'insecte', country: 'Mexique (Michoacán)', flags: ['mx'], continent: 'Amérique du Nord',
    lat: 19.6, lon: -100.25, icon: '🦋', habitat: "Forêts de sapins (en hiver)",
    clue: 'Un papillon orange et noir qui fait un immense voyage chaque automne.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/Danaus_plexippus_MHNT.jpg/960px-Danaus_plexippus_MHNT.jpg",
    credit: { author: "Didier Descouens", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Danaus_plexippus_MHNT.jpg" },
    stat: { label: 'Migration', value: "jusqu'à 4 000 km" },
    facts: [
      'Chaque automne, des millions de monarques volent du Canada et des États-Unis jusqu\'aux montagnes du Mexique.',
      "Aucun papillon ne fait l'aller-retour : il faut plusieurs générations pour boucler le voyage.",
    ],
  },
  {
    id: 'ours-polaire', name: 'Ours polaire', kind: 'mammifere', country: 'Canada (Churchill, baie d\'Hudson)', flags: ['ca'], continent: 'Amérique du Nord',
    lat: 58.77, lon: -94.17, icon: '❄️', habitat: 'Banquise arctique',
    clue: 'Le plus grand carnivore terrestre, au pelage blanc, qui chasse sur la banquise.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/6/66/Polar_Bear_-_Alaska_%28cropped%29.jpg",
    credit: { author: "Alan Wilson", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Polar_Bear_-_Alaska_(cropped).jpg" },
    stat: { label: 'Poids', value: "jusqu'à 700 kg" },
    facts: [
      'Sous sa fourrure blanche, sa peau est noire pour mieux capter la chaleur du soleil.',
      'Il chasse surtout les phoques, en les guettant près des trous dans la glace.',
    ],
  },
  {
    id: 'quetzal', name: 'Quetzal resplendissant', kind: 'oiseau', country: 'Costa Rica (Monteverde)', flags: ['cr'], continent: 'Amérique du Nord',
    lat: 10.3, lon: -84.8, icon: '🐦', habitat: 'Forêts de nuages',
    clue: 'Un oiseau vert brillant à très longue queue, sacré pour les Mayas et les Aztèques.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/057_Male_Resplendent_quetzal_in_Los_Quetzales_National_Park_Photo_by_Giles_Laurent.jpg/960px-057_Male_Resplendent_quetzal_in_Los_Quetzales_National_Park_Photo_by_Giles_Laurent.jpg",
    credit: { author: "Giles Laurent", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:057_Male_Resplendent_quetzal_in_Los_Quetzales_National_Park_Photo_by_Giles_Laurent.jpg" },
    stat: { label: 'Queue', value: "jusqu'à 65 cm" },
    facts: [
      'La monnaie du Guatemala s\'appelle le quetzal, en son honneur.',
      'Les Mayas et les Aztèques le considéraient comme sacré.',
    ],
  },
  {
    id: 'renard-polaire', name: 'Renard polaire', kind: 'mammifere', country: 'Canada (Nunavut)', flags: ['ca'], continent: 'Amérique du Nord',
    lat: 68.0, lon: -105.0, icon: '🦊', habitat: 'Toundra arctique',
    clue: 'Un petit renard dont le pelage devient tout blanc en hiver.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/Vulpes_lagopus_in_Iceland_%28cropped_3%29.jpg/960px-Vulpes_lagopus_in_Iceland_%28cropped_3%29.jpg",
    credit: { author: "Jonatan Pie (unsplash.com/@r3dmax)", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Vulpes_lagopus_in_Iceland_(cropped_3).jpg" },
    stat: { label: 'Froid supporté', value: "jusqu'à −50 °C" },
    facts: [
      'Son pelage change de couleur : brun en été, blanc en hiver.',
      'Il enroule sa queue touffue autour de lui pour dormir au chaud.',
    ],
  },
  {
    id: 'loutre-mer', name: 'Loutre de mer', kind: 'mammifere', country: 'États-Unis (baie de Monterey, Californie)', flags: ['us'], continent: 'Amérique du Nord',
    lat: 36.6, lon: -121.9, icon: '🦦', habitat: "Côtes et forêts d'algues",
    clue: 'Un petit mammifère marin qui flotte sur le dos et utilise des pierres comme outils.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Sea_Otter_%28Enhydra_lutris%29_%2825169790524%29_crop.jpg/500px-Sea_Otter_%28Enhydra_lutris%29_%2825169790524%29_crop.jpg",
    credit: { author: "Marshal Hedin from San Diego", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Sea_Otter_(Enhydra_lutris)_(25169790524)_crop.jpg" },
    stat: { label: 'Fourrure', value: 'la plus dense du monde' },
    facts: [
      "Elle dort sur le dos et s'enroule dans les algues pour ne pas dériver.",
      'Elle pose une pierre sur son ventre pour casser les coquillages.',
    ],
  },
  {
    id: 'chien-prairie', name: 'Chien de prairie', kind: 'mammifere', country: 'États-Unis (Grandes Plaines)', flags: ['us'], continent: 'Amérique du Nord',
    lat: 41.0, lon: -101.0, icon: '🐿️', habitat: 'Prairies',
    clue: 'Un petit rongeur qui vit dans d\'immenses « villes » souterraines.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Cynomys_ludovicianus18082009a.jpg/960px-Cynomys_ludovicianus18082009a.jpg",
    credit: { author: "Sylfred1977", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Cynomys_ludovicianus18082009a.jpg" },
    stat: { label: 'Taille', value: 'environ 35 cm' },
    facts: [
      "Ses terriers forment de véritables villes qui peuvent abriter des milliers d'animaux.",
      "Malgré son nom, ce n'est pas un chien : c'est une sorte d'écureuil terrestre !",
    ],
  },
  {
    id: 'crotale', name: 'Serpent à sonnette', kind: 'reptile', country: 'États-Unis (désert de Sonora, Arizona)', flags: ['us', 'mx'], continent: 'Amérique du Nord',
    lat: 32.3, lon: -111.0, icon: '🐍', habitat: 'Déserts',
    clue: 'Un serpent du désert qui agite le bout de sa queue pour faire du bruit.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Crotalus_atrox_USFWS.jpg/960px-Crotalus_atrox_USFWS.jpg",
    credit: { author: "Gary Stolz (original)", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Crotalus_atrox_USFWS.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 2 m" },
    facts: [
      "Sa « sonnette » est faite d'anneaux de kératine qui s'entrechoquent.",
      'Il sent la chaleur de ses proies grâce à de petites fossettes sur sa tête.',
    ],
  },

  // ------------------------------------------------------------- Amérique du Sud
  {
    id: 'paresseux', name: 'Paresseux à trois doigts', kind: 'mammifere', country: 'Brésil (Amazonie)', flags: ['br'], continent: 'Amérique du Sud',
    lat: -3.0, lon: -60.0, icon: '🦥', habitat: 'Forêt tropicale',
    clue: 'Un mammifère très lent qui passe sa vie suspendu la tête en bas dans les arbres.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Bradypus.jpg/960px-Bradypus.jpg",
    credit: { author: "Stefan Laube (Tauchgurke)", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Bradypus.jpg" },
    stat: { label: 'Vitesse', value: 'quelques mètres par minute' },
    facts: [
      'Il est si lent que des algues vertes poussent dans sa fourrure !',
      "Il ne descend de son arbre qu'environ une fois par semaine… pour faire ses besoins.",
    ],
  },
  {
    id: 'jaguar', name: 'Jaguar', kind: 'mammifere', country: 'Brésil (Pantanal)', flags: ['br'], continent: 'Amérique du Sud',
    lat: -17.5, lon: -57.0, icon: '🐆', habitat: 'Forêts et marais',
    clue: "Le plus grand félin d'Amérique, qui adore nager.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Jaguar_full.jpg/960px-Jaguar_full.jpg",
    credit: { author: "Hafiz Issadeen from Dharga Town, Sri Lanka", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Jaguar_full.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 150 kg" },
    facts: [
      'Sa morsure est si puissante qu\'elle peut percer une carapace de tortue.',
      'Ses taches ressemblent à des roses : on les appelle des rosettes.',
    ],
  },
  {
    id: 'vigogne', name: 'Vigogne', kind: 'mammifere', country: 'Pérou (Pampa Galeras)', flags: ['pe', 'bo'], continent: 'Amérique du Sud',
    lat: -14.7, lon: -74.4, icon: '🦙', habitat: 'Hauts plateaux des Andes',
    clue: 'Un petit cousin sauvage du lama, qui vit très haut dans les Andes.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Vicuna_%2889163948%29.jpg/960px-Vicuna_%2889163948%29.jpg",
    credit: { author: "Thomas Quine", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Vicuna_(89163948).jpg" },
    stat: { label: 'Altitude', value: '3 500 à 5 000 m' },
    facts: [
      "Sa laine est l'une des plus fines et des plus précieuses du monde.",
      "C'est l'animal national du Pérou : elle figure sur ses armoiries.",
    ],
  },
  {
    id: 'condor', name: 'Condor des Andes', kind: 'oiseau', country: 'Chili (Patagonie)', flags: ['cl', 'ar'], continent: 'Amérique du Sud',
    lat: -50.9, lon: -72.9, icon: '🦅', habitat: 'Montagnes des Andes',
    clue: "L'un des plus grands oiseaux volants du monde, qui plane au-dessus des Andes.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Vultur_gryphus_-Dou%C3%A9-la-Fontaine_Zoo%2C_France-8a.jpg/960px-Vultur_gryphus_-Dou%C3%A9-la-Fontaine_Zoo%2C_France-8a.jpg",
    credit: { author: "Emilio del Prado", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Vultur_gryphus_-Dou%C3%A9-la-Fontaine_Zoo,_France-8a.jpg" },
    stat: { label: 'Envergure', value: 'plus de 3 m' },
    facts: [
      'Il peut planer pendant des heures sans presque battre des ailes.',
      "Il se nourrit surtout d'animaux morts : c'est un vautour.",
    ],
  },
  {
    id: 'toucan', name: 'Toucan toco', kind: 'oiseau', country: 'Brésil et Argentine (Iguazú)', flags: ['br', 'ar'], continent: 'Amérique du Sud',
    lat: -25.6, lon: -54.4, icon: '🦜', habitat: 'Forêts et savanes',
    clue: 'Un oiseau au bec orange immense… et pourtant très léger.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg/960px-006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg",
    credit: { author: "Giles Laurent", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg" },
    stat: { label: 'Bec', value: "jusqu'à 20 cm" },
    facts: [
      "Son bec est creux à l'intérieur : il est très léger.",
      "Son bec l'aide aussi à se rafraîchir quand il fait chaud.",
    ],
  },
  {
    id: 'tortue-galapagos', name: 'Tortue géante des Galápagos', kind: 'reptile', country: 'Équateur (îles Galápagos)', flags: ['ec'], continent: 'Amérique du Sud',
    lat: -0.65, lon: -90.4, icon: '🐢', habitat: 'Îles volcaniques',
    clue: 'Une tortue géante qui peut vivre plus de 100 ans.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/Tortue_g%C3%A9ante.jpg/960px-Tortue_g%C3%A9ante.jpg",
    credit: { author: "Céréales Killer (Wikipédia en français)", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Tortue_g%C3%A9ante.jpg" },
    stat: { label: 'Poids', value: 'plus de 200 kg' },
    facts: [
      'Elle peut survivre presque un an sans manger ni boire !',
      'Le nom « Galápagos » vient d\'un vieux mot espagnol qui veut dire « tortue ».',
    ],
  },
  {
    id: 'iguane-marin', name: 'Iguane marin', kind: 'reptile', country: 'Équateur (île Fernandina, Galápagos)', flags: ['ec'], continent: 'Amérique du Sud',
    lat: -0.37, lon: -91.55, icon: '🦎', habitat: 'Côtes rocheuses volcaniques',
    clue: 'Le seul lézard au monde qui nage et se nourrit dans la mer.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Iguanamarina.jpg",
    credit: { author: "Auteur inconnu", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Iguanamarina.jpg" },
    stat: { label: 'Taille', value: "jusqu'à 1 m" },
    facts: [
      'Il broute les algues au fond de la mer.',
      "Il éternue pour rejeter le sel de la mer qu'il avale !",
    ],
  },
  {
    id: 'anaconda', name: 'Anaconda vert', kind: 'reptile', country: 'Venezuela (Llanos)', flags: ['ve', 'co'], continent: 'Amérique du Sud',
    lat: 7.5, lon: -68.0, icon: '🐍', habitat: 'Marais et rivières',
    clue: 'Le serpent le plus lourd du monde, qui vit dans les marais.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Eunectes_murinus.jpg",
    credit: { author: "Auteur inconnu", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Eunectes_murinus.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 100 kg" },
    facts: [
      "Il n'est pas venimeux : il étouffe ses proies en s'enroulant autour.",
      "Il passe beaucoup de temps dans l'eau, avec seulement les yeux et les narines qui dépassent.",
    ],
  },
  {
    id: 'dauphin-rose', name: "Dauphin rose de l'Amazone", kind: 'mammifere', country: 'Brésil (Amazonie, Mamirauá)', flags: ['br'], continent: 'Amérique du Sud',
    lat: -3.3, lon: -64.7, icon: '🐬', habitat: 'Fleuves et forêts inondées',
    clue: "Un dauphin rose qui vit dans un fleuve géant d'Amérique du Sud.",
    photo: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Inia-2.jpg",
    credit: { author: "Dennis Otten", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Inia-2.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 2,5 m" },
    facts: [
      'En vieillissant, il devient de plus en plus rose !',
      "Il nage entre les troncs d'arbres de la forêt inondée.",
    ],
  },
  {
    id: 'capybara', name: 'Capybara', kind: 'mammifere', country: "Argentine (marais de l'Iberá)", flags: ['ar'], continent: 'Amérique du Sud',
    lat: -28.5, lon: -57.2, icon: '🐾', habitat: 'Marais et bords de rivières',
    clue: 'Le plus gros rongeur du monde, qui adore barboter.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Familiepark_Harry_Malter_-_Capibara_-_13-07-2010_11-15-57.JPG/960px-Familiepark_Harry_Malter_-_Capibara_-_13-07-2010_11-15-57.JPG",
    credit: { author: "Paul Hermans", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Familiepark_Harry_Malter_-_Capibara_-_13-07-2010_11-15-57.JPG" },
    stat: { label: 'Poids', value: "jusqu'à 65 kg" },
    facts: [
      'Ses yeux, ses oreilles et ses narines sont en haut de la tête : il peut nager presque entièrement caché.',
      "Il est si calme que d'autres animaux, et même des oiseaux, s'installent sur son dos !",
    ],
  },
  {
    id: 'manchot-magellan', name: 'Manchot de Magellan', kind: 'oiseau', country: 'Argentine (Punta Tombo)', flags: ['ar'], continent: 'Amérique du Sud',
    lat: -44.05, lon: -65.2, icon: '🐧', habitat: 'Côtes',
    clue: "Un manchot qui vit sur les côtes d'Amérique du Sud, loin de la glace.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/135_-_Cap_Virgenes_-_Manchot_de_Magellan_-_Janvier_2010.JPG/960px-135_-_Cap_Virgenes_-_Manchot_de_Magellan_-_Janvier_2010.JPG",
    credit: { author: "Martin St-Amant (S23678)", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:135_-_Cap_Virgenes_-_Manchot_de_Magellan_-_Janvier_2010.JPG" },
    stat: { label: 'Taille', value: 'environ 70 cm' },
    facts: [
      'À Punta Tombo, en Argentine, des centaines de milliers de manchots viennent pondre chaque année.',
      "Il porte le nom de Magellan, le navigateur dont l'expédition l'a observé en 1520.",
    ],
  },
  {
    id: 'tortue-luth', name: 'Tortue luth', kind: 'reptile', country: 'Guyane (France)', flags: ['gf'], continent: 'Amérique du Sud',
    lat: 5.75, lon: -53.9, icon: '🐢', habitat: 'Haute mer (et plages pour pondre)',
    clue: 'La plus grande tortue marine, qui traverse les océans.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fc/Leatherback_sea_turtle_Tinglar%2C_USVI_%285839996547%29.jpg/960px-Leatherback_sea_turtle_Tinglar%2C_USVI_%285839996547%29.jpg",
    credit: { author: "U.S. Fish and Wildlife Service", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Leatherback_sea_turtle_Tinglar,_USVI_(5839996547).jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 2 m" },
    facts: [
      "Sa carapace n'est pas dure : elle est recouverte d'une peau épaisse, comme du cuir.",
      'Elle se nourrit surtout de méduses.',
    ],
  },
  {
    id: 'dendrobate', name: 'Grenouille dorée', kind: 'amphibien', country: 'Colombie (forêt du Chocó)', flags: ['co'], continent: 'Amérique du Sud',
    lat: 5.5, lon: -76.6, icon: '🐸', habitat: 'Forêt tropicale humide',
    clue: 'Une minuscule grenouille aux couleurs vives… et extrêmement toxique !',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Goldenergiftfrosch2cele4.jpg/960px-Goldenergiftfrosch2cele4.jpg",
    credit: { author: "Marcel Burkhard", license: "CC BY-SA 2.0 de", page: "https://commons.wikimedia.org/wiki/File:Goldenergiftfrosch2cele4.jpg" },
    stat: { label: 'Taille', value: 'environ 5 cm' },
    facts: [
      'Ses couleurs vives servent à prévenir : « Attention, je suis toxique ! »',
      'Des peuples indigènes utilisaient son poison pour leurs fléchettes de chasse.',
    ],
  },
  {
    id: 'ara', name: 'Ara rouge', kind: 'oiseau', country: 'Pérou (Amazonie, Tambopata)', flags: ['pe'], continent: 'Amérique du Sud',
    lat: -12.6, lon: -69.2, icon: '🦜', habitat: 'Forêt tropicale',
    clue: 'Un grand perroquet aux plumes rouges, jaunes et bleues.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/Scarlet_macaw_%28Ara_macao_cyanopterus%29_Copan.jpg/960px-Scarlet_macaw_%28Ara_macao_cyanopterus%29_Copan.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Scarlet_macaw_(Ara_macao_cyanopterus)_Copan.jpg" },
    stat: { label: 'Longévité', value: 'plus de 40 ans' },
    facts: [
      "Des centaines d'aras viennent grignoter l'argile des berges des rivières, sans doute pour ses sels minéraux.",
      'Son bec est si puissant qu\'il casse les noix les plus dures.',
    ],
  },
  {
    id: 'ibis-rouge', name: 'Ibis rouge', kind: 'oiseau', country: 'Trinité-et-Tobago (marais de Caroni)', flags: ['tt'], continent: 'Amérique du Sud',
    lat: 10.55, lon: -61.35, icon: '🐦', habitat: 'Mangroves et marais',
    clue: 'Un oiseau au plumage rouge vif, qui vit dans les mangroves.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/44/2016_Roter_Ibis.JPG/960px-2016_Roter_Ibis.JPG",
    credit: { author: "J. Patrick Fischer", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:2016_Roter_Ibis.JPG" },
    stat: { label: 'Couleur', value: 'rouge vif' },
    facts: [
      "C'est l'un des deux oiseaux nationaux de Trinité-et-Tobago.",
      'Comme le flamant rose, il doit sa couleur à sa nourriture : de petits crabes et crevettes.',
    ],
  },
  {
    id: 'tamanoir', name: 'Fourmilier géant', kind: 'mammifere', country: 'Brésil (Cerrado)', flags: ['br'], continent: 'Amérique du Sud',
    lat: -14.0, lon: -47.5, icon: '🐾', habitat: 'Savanes et prairies',
    clue: 'Un mammifère au museau très long qui avale des milliers de fourmis.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Myresluger.jpg",
    credit: { author: "Malene Thyssen", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Myresluger.jpg" },
    stat: { label: 'Langue', value: "jusqu'à 60 cm" },
    facts: [
      "Il peut avaler jusqu'à 30 000 fourmis et termites par jour !",
      "Il n'a pas de dents : il attrape les insectes avec sa langue collante.",
    ],
  },
  {
    id: 'ours-lunettes', name: 'Ours à lunettes', kind: 'mammifere', country: 'Andes (Équateur, Pérou, Colombie…)', flags: ['ec', 'pe'], continent: 'Amérique du Sud',
    lat: -0.5, lon: -78.3, icon: '🐻', habitat: 'Forêts de nuages des Andes',
    clue: "Le seul ours d'Amérique du Sud, avec des taches claires autour des yeux.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/2018-03-25_AT_Wien_13_Hietzing%2C_Tiergarten_Sch%C3%B6nbrunn%2C_Tremarctos_ornatus_%2845216502965%29.jpg/960px-2018-03-25_AT_Wien_13_Hietzing%2C_Tiergarten_Sch%C3%B6nbrunn%2C_Tremarctos_ornatus_%2845216502965%29.jpg",
    credit: { author: "Paul Korecky", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:2018-03-25_AT_Wien_13_Hietzing,_Tiergarten_Sch%C3%B6nbrunn,_Tremarctos_ornatus_(45216502965).jpg" },
    stat: { label: 'Poids', value: "jusqu'à 175 kg" },
    facts: [
      'Les taches claires autour de ses yeux ressemblent à des lunettes.',
      "C'est lui qui a inspiré l'ours Paddington, venu « du Pérou le plus sombre ».",
    ],
  },

  // ------------------------------------------------------------- Océanie
  {
    id: 'kangourou', name: 'Kangourou roux', kind: 'mammifere', country: 'Australie (centre)', flags: ['au'], continent: 'Océanie',
    lat: -24.0, lon: 135.0, icon: '🦘', habitat: 'Plaines sèches et déserts',
    clue: 'Un marsupial qui se déplace en faisant de grands bonds.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Red_kangaroo_-_melbourne_zoo.jpg/960px-Red_kangaroo_-_melbourne_zoo.jpg",
    credit: { author: "fir0002 (flagstaffotos)", license: "GFDL 1.2", page: "https://commons.wikimedia.org/wiki/File:Red_kangaroo_-_melbourne_zoo.jpg" },
    stat: { label: 'Bond', value: "jusqu'à 8 m" },
    facts: [
      'Son bébé, appelé joey, grandit dans la poche de sa maman.',
      'Il ne sait pas marcher à reculons !',
    ],
  },
  {
    id: 'koala', name: 'Koala', kind: 'mammifere', country: 'Australie (Queensland)', flags: ['au'], continent: 'Océanie',
    lat: -27.9, lon: 153.0, icon: '🐨', habitat: "Forêts d'eucalyptus",
    clue: "Un marsupial qui dort jusqu'à 20 heures par jour dans les arbres.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Koala_climbing_tree.jpg/960px-Koala_climbing_tree.jpg",
    credit: { author: "Diliff", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Koala_climbing_tree.jpg" },
    stat: { label: 'Sommeil', value: "jusqu'à 20 h par jour" },
    facts: [
      "Il mange presque uniquement des feuilles d'eucalyptus, toxiques pour la plupart des animaux.",
      "Ce n'est pas un ours : c'est un marsupial, comme le kangourou.",
    ],
  },
  {
    id: 'ornithorynque', name: 'Ornithorynque', kind: 'mammifere', country: 'Australie (Tasmanie)', flags: ['au'], continent: 'Océanie',
    lat: -41.9, lon: 146.5, icon: '🦆', habitat: 'Rivières et ruisseaux',
    clue: 'Un mammifère à bec de canard… qui pond des œufs !',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Ornithorhynchus.jpg/960px-Ornithorhynchus.jpg",
    credit: { author: "Dr. Philip Bethge", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Ornithorhynchus.jpg" },
    stat: { label: 'Taille', value: 'environ 50 cm' },
    facts: [
      'Le mâle a un ergot venimeux sur ses pattes arrière.',
      'Il chasse les yeux fermés, en sentant les petits signaux électriques de ses proies avec son bec.',
    ],
  },
  {
    id: 'kiwi', name: 'Kiwi', kind: 'oiseau', country: 'Nouvelle-Zélande', flags: ['nz'], continent: 'Océanie',
    lat: -38.9, lon: 175.6, icon: '🐦', habitat: 'Forêts',
    clue: 'Un oiseau qui ne vole pas et qui a des narines au bout de son long bec.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/Apteryx_mantelli_-Rotorua%2C_North_Island%2C_New_Zealand-8a.jpg/960px-Apteryx_mantelli_-Rotorua%2C_North_Island%2C_New_Zealand-8a.jpg",
    credit: { author: "The.Rohit", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Apteryx_mantelli_-Rotorua,_North_Island,_New_Zealand-8a.jpg" },
    stat: { label: 'Œuf', value: 'environ 20 % du poids de la maman' },
    facts: [
      'C\'est le symbole de la Nouvelle-Zélande : les Néo-Zélandais se surnomment eux-mêmes « Kiwis ».',
      'Ses narines sont au bout du bec : il trouve les vers à l\'odeur.',
    ],
  },
  {
    id: 'diable-tasmanie', name: 'Diable de Tasmanie', kind: 'mammifere', country: 'Australie (Tasmanie)', flags: ['au'], continent: 'Océanie',
    lat: -42.0, lon: 147.8, icon: '🐾', habitat: 'Forêts et buissons',
    clue: "Un petit marsupial noir au cri effrayant, qui vit sur une île au sud de l'Australie.",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ac/Tasmanian_devil_cropped.jpg/960px-Tasmanian_devil_cropped.jpg",
    credit: { author: "amdbergmann", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Tasmanian_devil_cropped.jpg" },
    stat: { label: 'Poids', value: "jusqu'à 12 kg" },
    facts: [
      "Sa morsure est l'une des plus puissantes du monde animal par rapport à sa taille.",
      "Il pousse des cris terribles quand il mange : c'est ce qui lui a valu son nom.",
    ],
  },
  {
    id: 'casoar', name: 'Casoar', kind: 'oiseau', country: 'Australie (forêt de Daintree)', flags: ['au', 'pg'], continent: 'Océanie',
    lat: -16.2, lon: 145.4, icon: '🐦', habitat: 'Forêt tropicale',
    clue: 'Un grand oiseau coureur avec un casque sur la tête, qui vit dans la forêt tropicale.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Casuarius_casuarius_-The_Rainforest_Habitat_Sanctuary-8a.jpg/960px-Casuarius_casuarius_-The_Rainforest_Habitat_Sanctuary-8a.jpg",
    credit: { author: "Michael Schmid", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Casuarius_casuarius_-The_Rainforest_Habitat_Sanctuary-8a.jpg" },
    stat: { label: 'Taille', value: "jusqu'à 1,8 m" },
    facts: [
      "Il a une griffe d'une douzaine de centimètres sur chaque patte : mieux vaut ne pas l'énerver !",
      "C'est le papa qui couve les œufs et élève les petits.",
    ],
  },
  {
    id: 'paradisier', name: 'Oiseau de paradis', kind: 'oiseau', country: 'Papouasie-Nouvelle-Guinée', flags: ['pg'], continent: 'Océanie',
    lat: -6.0, lon: 145.0, icon: '🐦', habitat: 'Forêt tropicale',
    clue: 'Un oiseau aux plumes extraordinaires, qui danse pour séduire.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/Raggiana_Bird-of-paradise_0A2A5379.jpg/960px-Raggiana_Bird-of-paradise_0A2A5379.jpg",
    credit: { author: "JJ Harrison", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Raggiana_Bird-of-paradise_0A2A5379.jpg" },
    stat: { label: 'Espèces', value: 'plus de 40' },
    facts: [
      'Les mâles dansent et déploient leurs plumes colorées pour impressionner les femelles.',
      'Il figure sur le drapeau de la Papouasie-Nouvelle-Guinée.',
    ],
  },
  {
    id: 'poisson-clown', name: 'Poisson-clown', kind: 'poisson', country: 'Australie (Grande Barrière de corail)', flags: ['au'], continent: 'Océanie',
    lat: -18.3, lon: 147.7, icon: '🐠', habitat: 'Récifs de corail',
    clue: 'Un petit poisson orange et blanc qui vit caché dans une anémone de mer.',
    photo: "https://upload.wikimedia.org/wikipedia/commons/9/94/Amphiprion_percula.JPG",
    credit: { author: "Haplochromis", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Amphiprion_percula.JPG" },
    stat: { label: 'Taille', value: 'environ 10 cm' },
    facts: [
      "Une couche de mucus le protège des piqûres de l'anémone.",
      'Tous les poissons-clowns naissent mâles ; le plus gros du groupe peut devenir femelle !',
    ],
  },
  {
    id: 'requin-baleine', name: 'Requin-baleine', kind: 'poisson', country: 'Australie (récif de Ningaloo)', flags: ['au'], continent: 'Océanie',
    lat: -22.7, lon: 113.7, icon: '🦈', habitat: 'Mers chaudes',
    clue: 'Le plus grand poisson du monde… totalement inoffensif.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Whale_shark_Georgia_aquarium.jpg/960px-Whale_shark_Georgia_aquarium.jpg",
    credit: { author: "Zac Wolf (recadrage : Stefan)", license: "CC BY-SA 2.5", page: "https://commons.wikimedia.org/wiki/File:Whale_shark_Georgia_aquarium.jpg" },
    stat: { label: 'Longueur', value: 'plus de 12 m' },
    facts: [
      'Il se nourrit de plancton, qu\'il filtre en ouvrant son énorme bouche.',
      'Chaque requin-baleine a des taches uniques, comme une empreinte digitale.',
    ],
  },
  {
    id: 'emeu', name: 'Émeu', kind: 'oiseau', country: 'Australie (Ouest)', flags: ['au'], continent: 'Océanie',
    lat: -30.0, lon: 120.0, icon: '🐦', habitat: 'Bush et plaines sèches',
    clue: 'Le deuxième plus grand oiseau du monde, qui court dans le bush australien.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Emu_1_-_Tidbinbilla.jpg/960px-Emu_1_-_Tidbinbilla.jpg",
    credit: { author: "JJ Harrison", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Emu_1_-_Tidbinbilla.jpg" },
    stat: { label: 'Vitesse', value: "jusqu'à 50 km/h" },
    facts: [
      "Comme l'autruche, il ne vole pas.",
      "C'est le papa qui couve les œufs, vert foncé, pendant environ 8 semaines, sans presque manger.",
    ],
  },

  // ------------------------------------------------------------- Océans et pôles
  {
    id: 'baleine-bleue', name: 'Baleine bleue', kind: 'mammifere', country: 'Océan Pacifique (au large du Chili)', flags: [], continent: 'Océans',
    lat: -43.5, lon: -74.5, icon: '🐋', habitat: 'Océans du monde entier',
    clue: 'Le plus grand animal ayant jamais vécu sur Terre.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg/960px-Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg",
    credit: { author: "NOAA Photo Library", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 30 m" },
    facts: [
      'Son cœur est aussi gros qu\'une petite voiture !',
      'Elle se nourrit de krill, de minuscules crevettes, dont elle avale plusieurs tonnes par jour.',
    ],
  },
  {
    id: 'requin-blanc', name: 'Grand requin blanc', kind: 'poisson', country: "Océan, au large de l'Afrique du Sud", flags: [], continent: 'Océans',
    lat: -34.8, lon: 19.6, icon: '🦈', habitat: 'Eaux côtières tempérées',
    clue: 'Le plus grand poisson prédateur des océans.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Great_White_Shark_%2814730820387%29.jpg/960px-Great_White_Shark_%2814730820387%29.jpg",
    credit: { author: "Elias Levy", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Great_White_Shark_(14730820387).jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 6 m" },
    facts: [
      'Il a plusieurs rangées de dents, qui repoussent toute sa vie.',
      'Son odorat est incroyable : il sent une toute petite goutte de sang dans une énorme quantité d\'eau.',
    ],
  },
  {
    id: 'narval', name: 'Narval', kind: 'mammifere', country: 'Océan Arctique (nord du Canada et Groenland)', flags: [], continent: 'Océans',
    lat: 74.3, lon: -84.0, icon: '🦄', habitat: "Eaux glacées de l'Arctique",
    clue: 'La « licorne des mers », qui porte une longue dent torsadée.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Pod_Monodon_monoceros.jpg/960px-Pod_Monodon_monoceros.jpg",
    credit: { author: "Dr. Kristin Laidre, Polar Science Center, UW NOAA/OAR/OER", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Pod_Monodon_monoceros.jpg" },
    stat: { label: 'Défense', value: "jusqu'à 3 m" },
    facts: [
      'Sa longue « corne » est en fait une dent qui traverse sa lèvre.',
      'Il peut plonger à plus de 1 500 m de profondeur.',
    ],
  },
  {
    id: 'manchot-empereur', name: 'Manchot empereur', kind: 'oiseau', country: 'Antarctique (Terre Adélie)', flags: [], continent: 'Océans',
    lat: -66.66, lon: 140.0, icon: '🐧', habitat: "Banquise de l'Antarctique",
    clue: "Le plus grand des manchots, qui élève ses petits au cœur de l'hiver polaire.",
    photo: "https://upload.wikimedia.org/wikipedia/commons/0/07/Emperor_Penguin_Manchot_empereur.jpg",
    credit: { author: "Samuel Blanc", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Emperor_Penguin_Manchot_empereur.jpg" },
    stat: { label: 'Taille', value: "jusqu'à 1,2 m" },
    facts: [
      "Pendant l'hiver, le papa garde l'œuf au chaud sur ses pattes pendant environ deux mois, sans manger.",
      'Pour se protéger du froid, les manchots se serrent les uns contre les autres et changent de place à tour de rôle.',
    ],
  },
  {
    id: 'baleine-bosse', name: 'Baleine à bosse', kind: 'mammifere', country: 'Océan Pacifique (Hawaï)', flags: [], continent: 'Océans',
    lat: 20.8, lon: -156.8, icon: '🐳', habitat: 'Océans du monde entier',
    clue: 'Une baleine célèbre pour ses chants et ses sauts spectaculaires.',
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/Humpback_stellwagen_edit.jpg/960px-Humpback_stellwagen_edit.jpg",
    credit: { author: "Whit Welles Wwelles14", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Humpback_stellwagen_edit.jpg" },
    stat: { label: 'Longueur', value: "jusqu'à 16 m" },
    facts: [
      'Les mâles chantent des mélodies complexes qui peuvent durer des heures.',
      'Chaque année, elles nagent des milliers de kilomètres entre les eaux froides et les eaux chaudes.',
    ],
  },
  {
    id: 'raie-manta', name: 'Raie manta', kind: 'poisson', country: 'Océan Indien (Maldives)', flags: ['mv'], continent: 'Océans',
    lat: 4.2, lon: 73.5, icon: '🐟', habitat: 'Mers chaudes',
    clue: "Un poisson géant et plat qui semble voler dans l'eau.",
    photo: "https://upload.wikimedia.org/wikipedia/commons/d/df/Manta_birostris-Thailand4.jpg",
    credit: { author: "jon hanson from london, UK", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Manta_birostris-Thailand4.jpg" },
    stat: { label: 'Envergure', value: "jusqu'à 7 m" },
    facts: [
      'Elle a le plus gros cerveau de tous les poissons, par rapport à sa taille.',
      'Malgré sa taille, elle se nourrit de minuscule plancton.',
    ],
  },
];
