// Convertit un code pays ISO (ex: "FR") en emoji drapeau 🇫🇷
function flagEmoji(code) {
  return code
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)));
}

// 64 pays répartis sur tous les continents
const COUNTRIES = [
  // ---------- EUROPE (20) ----------
  { code: "FR", name: "France", continent: "Europe", population: "68 millions", fact: "Célèbre pour la tour Eiffel et sa gastronomie, c'est le pays le plus visité au monde." },
  { code: "DE", name: "Allemagne", continent: "Europe", population: "84 millions", fact: "Pays le plus peuplé d'Europe de l'Ouest, connu pour ses voitures et ses châteaux de contes de fées." },
  { code: "ES", name: "Espagne", continent: "Europe", population: "47 millions", fact: "Célèbre pour le flamenco, la paella et ses longues plages ensoleillées." },
  { code: "IT", name: "Italie", continent: "Europe", population: "59 millions", fact: "Berceau de la pizza et des pâtes, avec des trésors comme Rome et Venise." },
  { code: "GB", name: "Royaume-Uni", continent: "Europe", population: "67 millions", fact: "Pays de Big Ben, des cabines téléphoniques rouges et des châteaux royaux." },
  { code: "PT", name: "Portugal", continent: "Europe", population: "10 millions", fact: "Connu pour ses carreaux d'azulejos colorés et ses grands navigateurs d'autrefois." },
  { code: "NL", name: "Pays-Bas", continent: "Europe", population: "18 millions", fact: "Pays plat célèbre pour ses champs de tulipes, ses moulins et son amour du vélo." },
  { code: "BE", name: "Belgique", continent: "Europe", population: "12 millions", fact: "Réputée pour son chocolat, ses gaufres et ses bandes dessinées." },
  { code: "CH", name: "Suisse", continent: "Europe", population: "9 millions", fact: "Pays des Alpes, du chocolat et des montres de précision." },
  { code: "SE", name: "Suède", continent: "Europe", population: "10 millions", fact: "Pays scandinave couvert de forêts et de lacs, patrie d'IKEA." },
  { code: "NO", name: "Norvège", continent: "Europe", population: "5 millions", fact: "Célèbre pour ses fjords spectaculaires et ses aurores boréales." },
  { code: "FI", name: "Finlande", continent: "Europe", population: "5,5 millions", fact: "Le pays aux mille lacs, considéré comme la patrie officielle du Père Noël." },
  { code: "DK", name: "Danemark", continent: "Europe", population: "6 millions", fact: "Petit royaume connu pour le vélo, le design et les contes d'Andersen." },
  { code: "PL", name: "Pologne", continent: "Europe", population: "38 millions", fact: "Pays d'Europe centrale avec de superbes villes historiques comme Cracovie." },
  { code: "GR", name: "Grèce", continent: "Europe", population: "10 millions", fact: "Berceau des Jeux Olympiques et de nombreux mythes de l'Antiquité." },
  { code: "IE", name: "Irlande", continent: "Europe", population: "5 millions", fact: "Île verte connue pour ses trèfles à quatre feuilles et ses légendes de lutins." },
  { code: "AT", name: "Autriche", continent: "Europe", population: "9 millions", fact: "Pays des Alpes, célèbre pour la musique classique de Mozart." },
  { code: "CZ", name: "République tchèque", continent: "Europe", population: "10,5 millions", fact: "Connue pour la ville de Prague, ses châteaux et ses ruelles pavées." },
  { code: "HU", name: "Hongrie", continent: "Europe", population: "10 millions", fact: "Pays d'Europe centrale traversé par le grand fleuve Danube." },
  { code: "IS", name: "Islande", continent: "Europe", population: "0,4 million", fact: "Île de feu et de glace, avec des volcans, des geysers et des glaciers." },

  // ---------- AFRIQUE (14) ----------
  { code: "EG", name: "Égypte", continent: "Afrique", population: "110 millions", fact: "Pays des pyramides, du Sphinx et du grand fleuve Nil." },
  { code: "MA", name: "Maroc", continent: "Afrique", population: "37 millions", fact: "Connu pour ses souks colorés et les dunes du désert du Sahara." },
  { code: "DZ", name: "Algérie", continent: "Afrique", population: "45 millions", fact: "Plus grand pays d'Afrique, en grande partie recouvert par le Sahara." },
  { code: "NG", name: "Nigeria", continent: "Afrique", population: "220 millions", fact: "Pays le plus peuplé d'Afrique, avec une immense industrie du cinéma." },
  { code: "ZA", name: "Afrique du Sud", continent: "Afrique", population: "60 millions", fact: "Pays aux trois capitales, célèbre pour ses safaris et sa faune sauvage." },
  { code: "KE", name: "Kenya", continent: "Afrique", population: "55 millions", fact: "Connu pour ses grandes savanes et la migration spectaculaire des gnous." },
  { code: "ET", name: "Éthiopie", continent: "Afrique", population: "120 millions", fact: "Un des berceaux de l'humanité, un pays qui n'a jamais été colonisé." },
  { code: "GH", name: "Ghana", continent: "Afrique", population: "33 millions", fact: "Ancien royaume de l'or, aujourd'hui grand producteur de cacao." },
  { code: "SN", name: "Sénégal", continent: "Afrique", population: "18 millions", fact: "Pays d'Afrique de l'Ouest réputé pour sa légendaire hospitalité, la Teranga." },
  { code: "TN", name: "Tunisie", continent: "Afrique", population: "12 millions", fact: "Petit pays d'Afrique du Nord bordé par la mer Méditerranée." },
  { code: "CM", name: "Cameroun", continent: "Afrique", population: "28 millions", fact: "Surnommé « l'Afrique en miniature » pour son incroyable diversité de paysages." },
  { code: "MG", name: "Madagascar", continent: "Afrique", population: "29 millions", fact: "Grande île où vivent des animaux uniques au monde, comme les lémuriens." },
  { code: "TZ", name: "Tanzanie", continent: "Afrique", population: "65 millions", fact: "Abrite le Kilimandjaro, le plus haut sommet d'Afrique." },
  { code: "CI", name: "Côte d'Ivoire", continent: "Afrique", population: "28 millions", fact: "Premier producteur mondial de fèves de cacao." },

  // ---------- ASIE (15) ----------
  { code: "CN", name: "Chine", continent: "Asie", population: "1,4 milliard", fact: "Pays le plus peuplé du monde, avec la Grande Muraille visible sur des milliers de kilomètres." },
  { code: "JP", name: "Japon", continent: "Asie", population: "124 millions", fact: "Pays des mangas, des fleurs de cerisier et des trains à très grande vitesse." },
  { code: "IN", name: "Inde", continent: "Asie", population: "1,4 milliard", fact: "Pays du Taj Mahal, avec une incroyable diversité de langues et de cultures." },
  { code: "KR", name: "Corée du Sud", continent: "Asie", population: "52 millions", fact: "Connue dans le monde entier pour la K-pop et sa technologie de pointe." },
  { code: "TH", name: "Thaïlande", continent: "Asie", population: "72 millions", fact: "Pays des temples dorés et des plages tropicales du Sud-Est asiatique." },
  { code: "VN", name: "Vietnam", continent: "Asie", population: "99 millions", fact: "Pays en forme de S, célèbre pour ses rizières en terrasses." },
  { code: "ID", name: "Indonésie", continent: "Asie", population: "275 millions", fact: "Plus grand archipel du monde, avec plus de 17 000 îles." },
  { code: "MY", name: "Malaisie", continent: "Asie", population: "33 millions", fact: "Connue pour les tours jumelles Petronas et sa jungle tropicale luxuriante." },
  { code: "PH", name: "Philippines", continent: "Asie", population: "115 millions", fact: "Archipel de plus de 7 000 îles dans l'océan Pacifique." },
  { code: "SA", name: "Arabie saoudite", continent: "Asie", population: "36 millions", fact: "Grand pays du désert qui abrite les villes saintes de La Mecque et Médine." },
  { code: "AE", name: "Émirats arabes unis", continent: "Asie", population: "10 millions", fact: "Pays du Golfe connu pour Dubaï et ses gratte-ciel futuristes." },
  { code: "TR", name: "Turquie", continent: "Europe et Asie", population: "85 millions", fact: "Pays à cheval sur deux continents, avec Istanbul comme pont entre l'Europe et l'Asie." },
  { code: "IL", name: "Israël", continent: "Asie", population: "9 millions", fact: "Petit pays du Moyen-Orient avec la ville sainte de Jérusalem." },
  { code: "PK", name: "Pakistan", continent: "Asie", population: "240 millions", fact: "Traversé par le fleuve Indus, il abrite le K2, deuxième plus haut sommet du monde." },
  { code: "MN", name: "Mongolie", continent: "Asie", population: "3,4 millions", fact: "Pays des grandes steppes, terre des nomades et des chevaux." },

  // ---------- AMÉRIQUES (12) ----------
  { code: "US", name: "États-Unis", continent: "Amérique du Nord", population: "335 millions", fact: "Pays du Grand Canyon, d'Hollywood et de la Statue de la Liberté." },
  { code: "CA", name: "Canada", continent: "Amérique du Nord", population: "39 millions", fact: "Deuxième plus grand pays du monde, connu pour ses érables et ses ours." },
  { code: "MX", name: "Mexique", continent: "Amérique du Nord", population: "128 millions", fact: "Pays des pyramides mayas et aztèques, et inventeur du chocolat chaud." },
  { code: "BR", name: "Brésil", continent: "Amérique du Sud", population: "216 millions", fact: "Plus grand pays d'Amérique du Sud, qui abrite une grande partie de la forêt amazonienne." },
  { code: "AR", name: "Argentine", continent: "Amérique du Sud", population: "46 millions", fact: "Célèbre pour le tango, le football et les grandes plaines de la pampa." },
  { code: "CL", name: "Chili", continent: "Amérique du Sud", population: "19 millions", fact: "Pays très long et étroit, qui contient le désert d'Atacama, un des plus secs au monde." },
  { code: "PE", name: "Pérou", continent: "Amérique du Sud", population: "34 millions", fact: "Abrite la cité perdue du Machu Picchu, perchée dans les Andes." },
  { code: "CO", name: "Colombie", continent: "Amérique du Sud", population: "52 millions", fact: "Pays d'Amérique du Sud réputé pour son café et son incroyable biodiversité." },
  { code: "CU", name: "Cuba", continent: "Amérique centrale", population: "11 millions", fact: "Île des Caraïbes connue pour ses vieilles voitures colorées et sa musique." },
  { code: "JM", name: "Jamaïque", continent: "Amérique centrale", population: "2,8 millions", fact: "Île natale du reggae et de nombreux champions olympiques de sprint." },
  { code: "CR", name: "Costa Rica", continent: "Amérique centrale", population: "5 millions", fact: "Pays sans armée, célèbre pour ses forêts tropicales très bien protégées." },
  { code: "UY", name: "Uruguay", continent: "Amérique du Sud", population: "3,4 millions", fact: "Petit pays connu pour ses plages et sa grande passion pour le football." },

  // ---------- OCÉANIE (3) ----------
  { code: "AU", name: "Australie", continent: "Océanie", population: "26 millions", fact: "Île-continent qui abrite kangourous, koalas et la Grande Barrière de corail." },
  { code: "NZ", name: "Nouvelle-Zélande", continent: "Océanie", population: "5 millions", fact: "Pays aux paysages spectaculaires, terre des Maoris et du rugby des All Blacks." },
  { code: "FJ", name: "Fidji", continent: "Océanie", population: "0,9 million", fact: "Archipel du Pacifique Sud composé de plus de 300 îles paradisiaques." },

  // ---------- EUROPE (16 de plus) ----------
  { code: "AL", name: "Albanie", continent: "Europe", population: "2,8 millions", fact: "Pays des Balkans dont le drapeau porte un aigle à deux têtes." },
  { code: "BY", name: "Biélorussie", continent: "Europe", population: "9,5 millions", fact: "Pays couvert de grandes forêts, ancienne république de l'URSS." },
  { code: "BA", name: "Bosnie-Herzégovine", continent: "Europe", population: "3,2 millions", fact: "Sa capitale Sarajevo a accueilli les Jeux olympiques d'hiver en 1984." },
  { code: "BG", name: "Bulgarie", continent: "Europe", population: "6,5 millions", fact: "Grand producteur mondial de roses utilisées en parfumerie." },
  { code: "HR", name: "Croatie", continent: "Europe", population: "3,9 millions", fact: "Longue côte sur la mer Adriatique, célèbre pour la ville de Dubrovnik." },
  { code: "EE", name: "Estonie", continent: "Europe", population: "1,3 million", fact: "Un des pays les plus numériques au monde, on peut même y voter en ligne." },
  { code: "LV", name: "Lettonie", continent: "Europe", population: "1,9 million", fact: "Pays balte couvert de forêts, de lacs et de plages de sable fin." },
  { code: "LT", name: "Lituanie", continent: "Europe", population: "2,7 millions", fact: "Connue pour son ambre doré ramassé le long de la mer Baltique." },
  { code: "LU", name: "Luxembourg", continent: "Europe", population: "0,65 million", fact: "Tout petit pays où l'on parle couramment trois langues officielles." },
  { code: "MT", name: "Malte", continent: "Europe", population: "0,5 million", fact: "Île méditerranéenne qui abrite certains des plus anciens temples du monde." },
  { code: "MC", name: "Monaco", continent: "Europe", population: "0,04 million", fact: "Deuxième plus petit État du monde, célèbre pour son Grand Prix de Formule 1." },
  { code: "RO", name: "Roumanie", continent: "Europe", population: "19 millions", fact: "Abrite en Transylvanie le célèbre château lié à la légende de Dracula." },
  { code: "RU", name: "Russie", continent: "Europe et Asie", population: "144 millions", fact: "Plus grand pays du monde, son territoire traverse onze fuseaux horaires." },
  { code: "RS", name: "Serbie", continent: "Europe", population: "6,7 millions", fact: "Pays des Balkans dont la capitale Belgrade est bâtie au confluent de deux fleuves." },
  { code: "SK", name: "Slovaquie", continent: "Europe", population: "5,4 millions", fact: "Pays montagneux célèbre pour ses nombreux châteaux médiévaux." },
  { code: "UA", name: "Ukraine", continent: "Europe", population: "environ 38 millions", fact: "Surnommée le « grenier à blé de l'Europe » pour ses immenses champs de céréales." },

  // ---------- AFRIQUE (16 de plus) ----------
  { code: "AO", name: "Angola", continent: "Afrique", population: "35 millions", fact: "Grand producteur africain de pétrole et de diamants." },
  { code: "BJ", name: "Bénin", continent: "Afrique", population: "13 millions", fact: "Considéré comme le berceau historique du culte vaudou." },
  { code: "BW", name: "Botswana", continent: "Afrique", population: "2,6 millions", fact: "Abrite le delta de l'Okavango, un immense oasis pour la faune sauvage." },
  { code: "BF", name: "Burkina Faso", continent: "Afrique", population: "22 millions", fact: "Pays sahélien d'Afrique de l'Ouest, sans accès à la mer." },
  { code: "CD", name: "République démocratique du Congo", continent: "Afrique", population: "100 millions", fact: "Abrite une grande partie de la deuxième plus vaste forêt tropicale du monde." },
  { code: "GA", name: "Gabon", continent: "Afrique", population: "2,3 millions", fact: "Presque entièrement recouvert d'une forêt équatoriale dense." },
  { code: "LY", name: "Libye", continent: "Afrique", population: "7 millions", fact: "Pays d'Afrique du Nord en grande partie recouvert par le désert du Sahara." },
  { code: "ML", name: "Mali", continent: "Afrique", population: "23 millions", fact: "Abrite la mythique cité de Tombouctou, ancien centre du savoir." },
  { code: "MU", name: "Maurice", continent: "Afrique", population: "1,3 million", fact: "Île paradisiaque de l'océan Indien réputée pour ses plages." },
  { code: "MZ", name: "Mozambique", continent: "Afrique", population: "33 millions", fact: "Longe une très grande côte sur l'océan Indien." },
  { code: "NA", name: "Namibie", continent: "Afrique", population: "2,6 millions", fact: "Célèbre pour les immenses dunes rouges du désert du Namib." },
  { code: "RW", name: "Rwanda", continent: "Afrique", population: "14 millions", fact: "Surnommé le « pays des mille collines »." },
  { code: "SD", name: "Soudan", continent: "Afrique", population: "46 millions", fact: "Traversé par le Nil, il compte plus de pyramides que l'Égypte." },
  { code: "TG", name: "Togo", continent: "Afrique", population: "9 millions", fact: "Petit pays étroit d'Afrique de l'Ouest bordé par l'océan Atlantique." },
  { code: "UG", name: "Ouganda", continent: "Afrique", population: "48 millions", fact: "Abrite les sources du Nil et des gorilles de montagne." },
  { code: "ZM", name: "Zambie", continent: "Afrique", population: "20 millions", fact: "Célèbre pour les impressionnantes chutes Victoria." },

  // ---------- ASIE (16 de plus) ----------
  { code: "AF", name: "Afghanistan", continent: "Asie", population: "40 millions", fact: "Pays montagneux d'Asie centrale au carrefour de nombreuses routes commerciales anciennes." },
  { code: "AM", name: "Arménie", continent: "Asie", population: "3 millions", fact: "Un des plus anciens pays chrétiens du monde." },
  { code: "AZ", name: "Azerbaïdjan", continent: "Asie", population: "10 millions", fact: "Surnommé le « pays du feu » à cause de ses flammes naturelles de gaz." },
  { code: "BD", name: "Bangladesh", continent: "Asie", population: "170 millions", fact: "Traversé par un immense delta formé par plusieurs grands fleuves." },
  { code: "BT", name: "Bhoutan", continent: "Asie", population: "0,8 million", fact: "Mesure le « bonheur national brut » de ses habitants plutôt que sa richesse." },
  { code: "BN", name: "Brunei", continent: "Asie", population: "0,45 million", fact: "Petit sultanat très riche en pétrole, situé sur l'île de Bornéo." },
  { code: "KH", name: "Cambodge", continent: "Asie", population: "17 millions", fact: "Abrite les majestueux temples d'Angkor." },
  { code: "GE", name: "Géorgie", continent: "Asie", population: "3,7 millions", fact: "Pays du Caucase, entre mer Noire et hautes montagnes." },
  { code: "IR", name: "Iran", continent: "Asie", population: "89 millions", fact: "Ancien empire perse, très riche en monuments antiques." },
  { code: "IQ", name: "Irak", continent: "Asie", population: "44 millions", fact: "Berceau d'anciennes civilisations, entre les fleuves Tigre et Euphrate." },
  { code: "JO", name: "Jordanie", continent: "Asie", population: "11 millions", fact: "Abrite la cité antique de Pétra, taillée dans la roche rose." },
  { code: "KZ", name: "Kazakhstan", continent: "Asie", population: "19 millions", fact: "Plus grand pays d'Asie centrale, en partie couvert de steppes immenses." },
  { code: "KW", name: "Koweït", continent: "Asie", population: "4,3 millions", fact: "Petit pays du Golfe très riche grâce au pétrole." },
  { code: "NP", name: "Népal", continent: "Asie", population: "30 millions", fact: "Abrite l'Everest, le plus haut sommet du monde." },
  { code: "SG", name: "Singapour", continent: "Asie", population: "5,9 millions", fact: "Cité-État ultramoderne d'Asie du Sud-Est, réputée pour sa propreté." },
  { code: "LK", name: "Sri Lanka", continent: "Asie", population: "22 millions", fact: "Île en forme de larme au sud de l'Inde, célèbre pour son thé." },

  // ---------- AMÉRIQUES (12 de plus) ----------
  { code: "BO", name: "Bolivie", continent: "Amérique du Sud", population: "12 millions", fact: "Abrite le plus grand désert de sel du monde, le Salar d'Uyuni." },
  { code: "EC", name: "Équateur", continent: "Amérique du Sud", population: "18 millions", fact: "Doit son nom à sa position, traversée par la ligne de l'équateur." },
  { code: "PY", name: "Paraguay", continent: "Amérique du Sud", population: "7 millions", fact: "Pays d'Amérique du Sud sans accès direct à la mer." },
  { code: "VE", name: "Venezuela", continent: "Amérique du Sud", population: "28 millions", fact: "Abrite Angel Falls, la plus haute chute d'eau du monde." },
  { code: "PA", name: "Panama", continent: "Amérique centrale", population: "4,4 millions", fact: "Traversé par le célèbre canal qui relie l'océan Atlantique au Pacifique." },
  { code: "GT", name: "Guatemala", continent: "Amérique centrale", population: "18 millions", fact: "Ancien cœur de la grande civilisation maya." },
  { code: "HN", name: "Honduras", continent: "Amérique centrale", population: "10 millions", fact: "Célèbre pour les ruines mayas de Copán." },
  { code: "NI", name: "Nicaragua", continent: "Amérique centrale", population: "6,8 millions", fact: "Pays d'Amérique centrale connu pour ses volcans et ses grands lacs." },
  { code: "SV", name: "Salvador", continent: "Amérique centrale", population: "6,3 millions", fact: "Le plus petit pays d'Amérique centrale." },
  { code: "DO", name: "République dominicaine", continent: "Amérique centrale", population: "11 millions", fact: "Partage une île des Caraïbes avec Haïti." },
  { code: "HT", name: "Haïti", continent: "Amérique centrale", population: "11 millions", fact: "Première république au monde dirigée par d'anciens esclaves libérés." },
  { code: "BS", name: "Bahamas", continent: "Amérique centrale", population: "0,4 million", fact: "Archipel de plus de 700 îles aux eaux turquoise des Caraïbes." },

  // ---------- OCÉANIE (4 de plus) ----------
  { code: "PG", name: "Papouasie-Nouvelle-Guinée", continent: "Océanie", population: "10 millions", fact: "Une des régions les plus diverses culturellement, avec plus de 800 langues parlées." },
  { code: "WS", name: "Samoa", continent: "Océanie", population: "0,22 million", fact: "Archipel polynésien du Pacifique Sud." },
  { code: "VU", name: "Vanuatu", continent: "Océanie", population: "0,33 million", fact: "Archipel volcanique du Pacifique connu pour ses fonds marins." },
  { code: "SB", name: "Îles Salomon", continent: "Océanie", population: "0,74 million", fact: "Des centaines d'îles éparpillées dans le Pacifique Sud." },
];
