// ============================================================================
// Les animaux du quiz : 64 animaux communs (dessins) et 64 animaux rares
// (photos, tout en bas du fichier).
//
// Les dessins viennent de "Noto Emoji" de Google (licence Apache 2.0),
// servis par les serveurs de Google Fonts. Chaque image est nommée d'après le
// code Unicode de l'émoji correspondant (séquences séparées par "_").
// ============================================================================

const IMAGE_BASE = "https://fonts.gstatic.com/s/e/notoemoji/latest/";

// Un animal rare a sa propre photo, un animal commun un dessin Noto
export const imageUrl = (animal) => animal.photo || `${IMAGE_BASE}${animal.img}/emoji.svg`;

// "the" = le nom avec son article, pour la question "Où est… ?"
export const ANIMALS = [
  { id: "chien",        name: "Chien",         the: "le chien",         img: "1f415" },
  { id: "chat",         name: "Chat",          the: "le chat",          img: "1f408" },
  { id: "cheval",       name: "Cheval",        the: "le cheval",        img: "1f40e" },
  { id: "vache",        name: "Vache",         the: "la vache",         img: "1f404" },
  { id: "cochon",       name: "Cochon",        the: "le cochon",        img: "1f416" },
  { id: "mouton",       name: "Mouton",        the: "le mouton",        img: "1f411" },
  { id: "chevre",       name: "Chèvre",        the: "la chèvre",        img: "1f410" },
  { id: "poule",        name: "Poule",         the: "la poule",         img: "1f414" },
  { id: "canard",       name: "Canard",        the: "le canard",        img: "1f986" },
  { id: "lapin",        name: "Lapin",         the: "le lapin",         img: "1f407" },
  { id: "souris",       name: "Souris",        the: "la souris",        img: "1f401" },
  { id: "ecureuil",     name: "Écureuil",      the: "l'écureuil",       img: "1f43f" },
  { id: "herisson",     name: "Hérisson",      the: "le hérisson",      img: "1f994" },
  { id: "chauvesouris", name: "Chauve-souris", the: "la chauve-souris", img: "1f987" },
  { id: "hibou",        name: "Hibou",         the: "le hibou",         img: "1f989" },
  { id: "aigle",        name: "Aigle",         the: "l'aigle",          img: "1f985" },
  { id: "perroquet",    name: "Perroquet",     the: "le perroquet",     img: "1f99c" },
  { id: "paon",         name: "Paon",          the: "le paon",          img: "1f99a" },
  { id: "flamant",      name: "Flamant rose",  the: "le flamant rose",  img: "1f9a9" },
  { id: "manchot",      name: "Manchot",       the: "le manchot",       img: "1f427" },
  { id: "cygne",        name: "Cygne",         the: "le cygne",         img: "1f9a2" },
  { id: "dinde",        name: "Dinde",         the: "la dinde",         img: "1f983" },
  { id: "elephant",     name: "Éléphant",      the: "l'éléphant",       img: "1f418" },
  { id: "girafe",       name: "Girafe",        the: "la girafe",        img: "1f992" },
  { id: "zebre",        name: "Zèbre",         the: "le zèbre",         img: "1f993" },
  { id: "rhinoceros",   name: "Rhinocéros",    the: "le rhinocéros",    img: "1f98f" },
  { id: "hippopotame",  name: "Hippopotame",   the: "l'hippopotame",    img: "1f99b" },
  { id: "chameau",      name: "Chameau",       the: "le chameau",       img: "1f42b" },
  { id: "kangourou",    name: "Kangourou",     the: "le kangourou",     img: "1f998" },
  { id: "gorille",      name: "Gorille",       the: "le gorille",       img: "1f98d" },
  { id: "orangoutan",   name: "Orang-outan",   the: "l'orang-outan",    img: "1f9a7" },
  { id: "lion",         name: "Lion",          the: "le lion",          img: "1f981" },
  { id: "tigre",        name: "Tigre",         the: "le tigre",         img: "1f405" },
  { id: "leopard",      name: "Léopard",       the: "le léopard",       img: "1f406" },
  { id: "ours",         name: "Ours",          the: "l'ours",           img: "1f43b" },
  { id: "ourspolaire",  name: "Ours polaire",  the: "l'ours polaire",   img: "1f43b_200d_2744_fe0f" },
  { id: "panda",        name: "Panda",         the: "le panda",         img: "1f43c" },
  { id: "koala",        name: "Koala",         the: "le koala",         img: "1f428" },
  { id: "renard",       name: "Renard",        the: "le renard",        img: "1f98a" },
  { id: "loup",         name: "Loup",          the: "le loup",          img: "1f43a" },
  { id: "raton",        name: "Raton laveur",  the: "le raton laveur",  img: "1f99d" },
  { id: "loutre",       name: "Loutre",        the: "la loutre",        img: "1f9a6" },
  { id: "paresseux",    name: "Paresseux",     the: "le paresseux",     img: "1f9a5" },
  { id: "mouffette",    name: "Mouffette",     the: "la mouffette",     img: "1f9a8" },
  { id: "castor",       name: "Castor",        the: "le castor",        img: "1f9ab" },
  { id: "cerf",         name: "Cerf",          the: "le cerf",          img: "1f98c" },
  { id: "bison",        name: "Bison",         the: "le bison",         img: "1f9ac" },
  { id: "lama",         name: "Lama",          the: "le lama",          img: "1f999" },
  { id: "crocodile",    name: "Crocodile",     the: "le crocodile",     img: "1f40a" },
  { id: "tortue",       name: "Tortue",        the: "la tortue",        img: "1f422" },
  { id: "lezard",       name: "Lézard",        the: "le lézard",        img: "1f98e" },
  { id: "serpent",      name: "Serpent",       the: "le serpent",       img: "1f40d" },
  { id: "grenouille",   name: "Grenouille",    the: "la grenouille",    img: "1f438" },
  { id: "dauphin",      name: "Dauphin",       the: "le dauphin",       img: "1f42c" },
  { id: "baleine",      name: "Baleine",       the: "la baleine",       img: "1f433" },
  { id: "requin",       name: "Requin",        the: "le requin",        img: "1f988" },
  { id: "pieuvre",      name: "Pieuvre",       the: "la pieuvre",       img: "1f419" },
  { id: "crabe",        name: "Crabe",         the: "le crabe",         img: "1f980" },
  { id: "poissonglobe", name: "Poisson-globe", the: "le poisson-globe", img: "1f421" },
  { id: "phoque",       name: "Phoque",        the: "le phoque",        img: "1f9ad" },
  { id: "escargot",     name: "Escargot",      the: "l'escargot",       img: "1f40c" },
  { id: "papillon",     name: "Papillon",      the: "le papillon",      img: "1f98b" },
  { id: "abeille",      name: "Abeille",       the: "l'abeille",        img: "1f41d" },
  { id: "coccinelle",   name: "Coccinelle",    the: "la coccinelle",    img: "1f41e" },
];

// ============================================================================
// Les 64 animaux RARES : ici ce sont de vraies photos, venant de Wikimedia
// Commons. Elles sont libres de droits à condition de citer leur auteur :
// "credit" est affiché sur la page credits.html.
// ============================================================================
export const RARE_ANIMALS = [
  { id: "narval", name: "Narval", the: "le narval",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Pod_Monodon_monoceros.jpg/330px-Pod_Monodon_monoceros.jpg",
    credit: { author: "Dr. Kristin Laidre, Polar Science Center, UW NOAA/OAR/OER", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Pod_Monodon_monoceros.jpg" } },
  { id: "tatou", name: "Tatou", the: "le tatou",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Dasypus_novemcinctus_en_Zool%C3%B3gico_de_Paraguan%C3%A1.jpg/330px-Dasypus_novemcinctus_en_Zool%C3%B3gico_de_Paraguan%C3%A1.jpg",
    credit: { author: "Aramburu Carlos", license: "CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:Dasypus_novemcinctus_en_Zool%C3%B3gico_de_Paraguan%C3%A1.jpg" } },
  { id: "vautour", name: "Vautour", the: "le vautour",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Griffon_Vulture_Portrait_%2816779138617%29.jpg/330px-Griffon_Vulture_Portrait_%2816779138617%29.jpg",
    credit: { author: "mhx from London, United Kingdom", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Griffon_Vulture_Portrait_(16779138617).jpg" } },
  { id: "ornithorynque", name: "Ornithorynque", the: "l'ornithorynque",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/Duck-billed_platypus_%28Ornithorhynchus_anatinus%29_Scottsdale_4.jpg/330px-Duck-billed_platypus_%28Ornithorhynchus_anatinus%29_Scottsdale_4.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Duck-billed_platypus_(Ornithorhynchus_anatinus)_Scottsdale_4.jpg" } },
  { id: "fourmilier", name: "Fourmilier", the: "le fourmilier",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Myresluger2.jpg/330px-Myresluger2.jpg",
    credit: { author: "Malene Thyssen", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Myresluger2.jpg" } },
  { id: "okapi", name: "Okapi", the: "l'okapi",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Saint-Aignan_%28Loir-et-Cher%29._Okapi.jpg/330px-Saint-Aignan_%28Loir-et-Cher%29._Okapi.jpg",
    credit: { author: "Daniel Jolivet", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Saint-Aignan_(Loir-et-Cher)._Okapi.jpg" } },
  { id: "pangolin", name: "Pangolin", the: "le pangolin",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Pangolin_%2851837575293%29.jpg/330px-Pangolin_%2851837575293%29.jpg",
    credit: { author: "flowcomm", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Pangolin_(51837575293).jpg" } },
  { id: "axolotl", name: "Axolotl", the: "l'axolotl",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Axolotl_ganz.jpg/330px-Axolotl_ganz.jpg",
    credit: { author: "LoKiLeCh", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Axolotl_ganz.jpg" } },
  { id: "tarsier", name: "Tarsier", the: "le tarsier",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Philippine_tarsier_%28Carlito_syrichta_fraterculus%29_Bohol.jpg/330px-Philippine_tarsier_%28Carlito_syrichta_fraterculus%29_Bohol.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Philippine_tarsier_(Carlito_syrichta_fraterculus)_Bohol.jpg" } },
  { id: "ayeaye", name: "Aye-aye", the: "l'aye-aye",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Wild_aye_aye.jpg/330px-Wild_aye_aye.jpg",
    credit: { author: "nomis-simon", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Wild_aye_aye.jpg" } },
  { id: "nasique", name: "Nasique", the: "le nasique",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Proboscis_Monkey_in_Borneo.jpg/330px-Proboscis_Monkey_in_Borneo.jpg",
    credit: { author: "David Dennis", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Proboscis_Monkey_in_Borneo.jpg" } },
  { id: "quokka", name: "Quokka", the: "le quokka",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Setonix_brachyurus_on_Rottnest_Island_1.jpg/330px-Setonix_brachyurus_on_Rottnest_Island_1.jpg",
    credit: { author: "Christophe95", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Setonix_brachyurus_on_Rottnest_Island_1.jpg" } },
  { id: "becensabot", name: "Bec-en-sabot", the: "le bec-en-sabot",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Balaeniceps_rex_-Ueno_Zoo%2C_Tokyo%2C_Japan-8a.jpg/330px-Balaeniceps_rex_-Ueno_Zoo%2C_Tokyo%2C_Japan-8a.jpg",
    credit: { author: "Bob Owen", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Balaeniceps_rex_-Ueno_Zoo,_Tokyo,_Japan-8a.jpg" } },
  { id: "blobfish", name: "Blobfish", the: "le blobfish",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Two_Psychrolutes_marcidus.jpg/330px-Two_Psychrolutes_marcidus.jpg",
    credit: { author: "Rachel Caauwe", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Two_Psychrolutes_marcidus.jpg" } },
  { id: "pandaroux", name: "Panda roux", the: "le panda roux",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Red_Panda%2C_Gentle_Tree-Dweller_of_the_Himalayas.jpg/330px-Red_Panda%2C_Gentle_Tree-Dweller_of_the_Himalayas.jpg",
    credit: { author: "Sunuwargr", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Red_Panda,_Gentle_Tree-Dweller_of_the_Himalayas.jpg" } },
  { id: "fennec", name: "Fennec", the: "le fennec",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Fennec_Fox_Vulpes_zerda.jpg/330px-Fennec_Fox_Vulpes_zerda.jpg",
    credit: { author: "Drew Avery", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Fennec_Fox_Vulpes_zerda.jpg" } },
  { id: "suricate", name: "Suricate", the: "le suricate",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Meerkat_%28Suricata_suricatta%29_Tswalu.jpg/330px-Meerkat_%28Suricata_suricatta%29_Tswalu.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Meerkat_(Suricata_suricatta)_Tswalu.jpg" } },
  { id: "capybara", name: "Capybara", the: "le capybara",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/71/Capybaracropped.jpg/330px-Capybaracropped.jpg",
    credit: { author: "Giles Laurent", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Capybaracropped.jpg" } },
  { id: "tapir", name: "Tapir", the: "le tapir",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/58/Schabrackentapir_Tapirus_indicus_Tiergarten-Nuernberg-1.jpg/330px-Schabrackentapir_Tapirus_indicus_Tiergarten-Nuernberg-1.jpg",
    credit: { author: "Rufus46", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Schabrackentapir_Tapirus_indicus_Tiergarten-Nuernberg-1.jpg" } },
  { id: "echidne", name: "Échidné", the: "l'échidné",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c9/Wild_shortbeak_echidna.jpg/330px-Wild_shortbeak_echidna.jpg",
    credit: { author: "User:Fir0002", license: "GFDL 1.2", page: "https://commons.wikimedia.org/wiki/File:Wild_shortbeak_echidna.jpg" } },
  { id: "wombat", name: "Wombat", the: "le wombat",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Vombatus_ursinus_-Maria_Island_National_Park.jpg/330px-Vombatus_ursinus_-Maria_Island_National_Park.jpg",
    credit: { author: "JJ Harrison (jjharrison89@facebook.com)", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Vombatus_ursinus_-Maria_Island_National_Park.jpg" } },
  { id: "diable", name: "Diable de Tasmanie", the: "le diable de Tasmanie",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Sarcophilus_harrisii_taranna.jpg/330px-Sarcophilus_harrisii_taranna.jpg",
    credit: { author: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Sarcophilus_harrisii_taranna.jpg" } },
  { id: "kiwi", name: "Kiwi", the: "le kiwi",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/TeTuatahianui.jpg/330px-TeTuatahianui.jpg",
    credit: { author: "Maungatautari Ecological Island Trust", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:TeTuatahianui.jpg" } },
  { id: "casoar", name: "Casoar", the: "le casoar",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Southern_Cassowary_7071.jpg/330px-Southern_Cassowary_7071.jpg",
    credit: { author: "Summerdrought", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Southern_Cassowary_7071.jpg" } },
  { id: "komodo", name: "Dragon de Komodo", the: "le dragon de Komodo",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/202306_Varanus_komodoensis.jpg/330px-202306_Varanus_komodoensis.jpg",
    credit: { author: "James Jolokia (james1203)", license: "CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:202306_Varanus_komodoensis.jpg" } },
  { id: "cameleon", name: "Caméléon", the: "le caméléon",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Panther_chameleon_%28Furcifer_pardalis%29_male_Nosy_Be.jpg/330px-Panther_chameleon_%28Furcifer_pardalis%29_male_Nosy_Be.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Panther_chameleon_(Furcifer_pardalis)_male_Nosy_Be.jpg" } },
  { id: "loris", name: "Loris", the: "le loris",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Nycticebus_coucang_002.jpg/330px-Nycticebus_coucang_002.jpg",
    credit: { author: "David Haring / Duke Lemur Center", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Nycticebus_coucang_002.jpg" } },
  { id: "lemurien", name: "Lémurien", the: "le lémurien",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Ring-tailed_lemur_%28Lemur_catta%29.jpg/330px-Ring-tailed_lemur_%28Lemur_catta%29.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Ring-tailed_lemur_(Lemur_catta).jpg" } },
  { id: "harfang", name: "Harfang des neiges", the: "le harfang des neiges",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/Bubo_scandiacus_%28Linnaeus%2C_1758%29_Male.jpg/330px-Bubo_scandiacus_%28Linnaeus%2C_1758%29_Male.jpg",
    credit: { author: "Michael Gäbler", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Bubo_scandiacus_(Linnaeus,_1758)_Male.jpg" } },
  { id: "toucan", name: "Toucan", the: "le toucan",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg/330px-006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg",
    credit: { author: "Giles Laurent", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:006_Toco_toucan_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg" } },
  { id: "calao", name: "Calao", the: "le calao",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg/330px-Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg",
    credit: { author: "Shantanu Kuveskar", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Great_hornbill_Photograph_by_Shantanu_Kuveskar.jpg" } },
  { id: "macareux", name: "Macareux", the: "le macareux",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Puffin_%28Fratercula_arctica%29.jpg/330px-Puffin_%28Fratercula_arctica%29.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Puffin_(Fratercula_arctica).jpg" } },
  { id: "albatros", name: "Albatros", the: "l'albatros",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Diomedea_exulans_-_SE_Tasmania.jpg/330px-Diomedea_exulans_-_SE_Tasmania.jpg",
    credit: { author: "JJ Harrison (https://www.jjharrison.com.au/)", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Diomedea_exulans_-_SE_Tasmania.jpg" } },
  { id: "ibis", name: "Ibis rouge", the: "l'ibis rouge",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Oceanografic_Scarlet_Ibis_02.jpg/330px-Oceanografic_Scarlet_Ibis_02.jpg",
    credit: { author: "Rafa Esteve", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Oceanografic_Scarlet_Ibis_02.jpg" } },
  { id: "colibri", name: "Colibri", the: "le colibri",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7c/Archilochus_colubris_-flying_-male-8.jpg/330px-Archilochus_colubris_-flying_-male-8.jpg",
    credit: { author: "jeffreyw", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Archilochus_colubris_-flying_-male-8.jpg" } },
  { id: "condor", name: "Condor", the: "le condor",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/AndeanCondorMale.jpg/330px-AndeanCondorMale.jpg",
    credit: { author: "Greg Hume", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:AndeanCondorMale.jpg" } },
  { id: "morse", name: "Morse", the: "le morse",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Walrus_in_the_Russian_Arctic_National_Park%2C_Novaya_Zemlya_2015-2.jpg/330px-Walrus_in_the_Russian_Arctic_National_Park%2C_Novaya_Zemlya_2015-2.jpg",
    credit: { author: "Nixette", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Walrus_in_the_Russian_Arctic_National_Park,_Novaya_Zemlya_2015-2.jpg" } },
  { id: "lamantin", name: "Lamantin", the: "le lamantin",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/99/Manatee_with_calf.PD_-_colour_corrected.jpg/330px-Manatee_with_calf.PD_-_colour_corrected.jpg",
    credit: { author: "Galen Rathbun", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Manatee_with_calf.PD_-_colour_corrected.jpg" } },
  { id: "beluga", name: "Béluga", the: "le béluga",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e8/Oceanogr%C3%A0fic_29102004.jpg/330px-Oceanogr%C3%A0fic_29102004.jpg",
    credit: { author: "Javier Yaya Tur / CIUDAD DE LAS ARTES Y LAS CIENCIAS from Valencia, España", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Oceanogr%C3%A0fic_29102004.jpg" } },
  { id: "orque", name: "Orque", the: "l'orque",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Killerwhales_jumping.jpg/330px-Killerwhales_jumping.jpg",
    credit: { author: "Robert Pittman", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Killerwhales_jumping.jpg" } },
  { id: "hippocampe", name: "Hippocampe", the: "l'hippocampe",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/25/Hippocampus_hippocampus_%28on_Ascophyllum_nodosum%29.jpg/330px-Hippocampus_hippocampus_%28on_Ascophyllum_nodosum%29.jpg",
    credit: { author: "Hans Hillewaert", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Hippocampus_hippocampus_(on_Ascophyllum_nodosum).jpg" } },
  { id: "poissonlune", name: "Poisson-lune", the: "le poisson-lune",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Mola_mola.jpg/330px-Mola_mola.jpg",
    credit: { author: "U.S. National Oceanic and Atmospheric Administration", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Mola_mola.jpg" } },
  { id: "raiemanta", name: "Raie manta", the: "la raie manta",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Manta_birostris-Thailand4.jpg/330px-Manta_birostris-Thailand4.jpg",
    credit: { author: "jon hanson from london, UK", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Manta_birostris-Thailand4.jpg" } },
  { id: "requinmarteau", name: "Requin-marteau", the: "le requin-marteau",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Great_hammerhead2.jpg/330px-Great_hammerhead2.jpg",
    credit: { author: "Albert kok", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Great_hammerhead2.jpg" } },
  { id: "nautile", name: "Nautile", the: "le nautile",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/Nautilus_pompilius_%28detail%29.jpg/330px-Nautilus_pompilius_%28detail%29.jpg",
    credit: { author: "Hans Hillewaert", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Nautilus_pompilius_(detail).jpg" } },
  { id: "poissonlion", name: "Poisson-lion", the: "le poisson-lion",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Pterois_volitans_Manado-e_edit.jpg/330px-Pterois_volitans_Manado-e_edit.jpg",
    credit: { author: "Photo by Jens Petersen, Edited by User:Olegiwit (cloned in part of fins) and Fir0002 (removed spots and noise)", license: "CC BY 2.5", page: "https://commons.wikimedia.org/wiki/File:Pterois_volitans_Manado-e_edit.jpg" } },
  { id: "limule", name: "Limule", the: "la limule",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Limulus_polyphemus_%28aq.%29.jpg/330px-Limulus_polyphemus_%28aq.%29.jpg",
    credit: { author: "Hans Hillewaert", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Limulus_polyphemus_(aq.).jpg" } },
  { id: "mante", name: "Mante religieuse", the: "la mante religieuse",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/62/European_praying_mantis_%28Mantis_religiosa%29_green_female_Dobruja.jpg/330px-European_praying_mantis_%28Mantis_religiosa%29_green_female_Dobruja.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:European_praying_mantis_(Mantis_religiosa)_green_female_Dobruja.jpg" } },
  { id: "phasme", name: "Phasme", the: "le phasme",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e6/A_Stick_Bug_in_Texas.jpg/330px-A_Stick_Bug_in_Texas.jpg",
    credit: { author: "Texas Lane", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:A_Stick_Bug_in_Texas.jpg" } },
  { id: "tardigrade", name: "Tardigrade", the: "le tardigrade",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/SEM_image_of_Milnesium_tardigradum_in_active_state_-_journal.pone.0045682.g001-2_%28white_background%29.png/330px-SEM_image_of_Milnesium_tardigradum_in_active_state_-_journal.pone.0045682.g001-2_%28white_background%29.png",
    credit: { author: "Schokraie E, Warnken U, Hotz-Wagenblatt A, Grohme MA, Hengherr S, et al. (2012)", license: "CC BY 2.5", page: "https://commons.wikimedia.org/wiki/File:SEM_image_of_Milnesium_tardigradum_in_active_state_-_journal.pone.0045682.g001-2_(white_background).png" } },
  { id: "gavial", name: "Gavial", the: "le gavial",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Gharial_%28Gavialis_gangeticus%29_male.jpg/330px-Gharial_%28Gavialis_gangeticus%29_male.jpg",
    credit: { author: "Charles J. Sharp", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Gharial_(Gavialis_gangeticus)_male.jpg" } },
  { id: "iguanemarin", name: "Iguane marin", the: "l'iguane marin",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Amblyrhynchus_cristatus_%283838137696%29.jpg/330px-Amblyrhynchus_cristatus_%283838137696%29.jpg",
    credit: { author: "RAF-YYC from Calgary, Canada", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Amblyrhynchus_cristatus_(3838137696).jpg" } },
  { id: "tortueluth", name: "Tortue luth", the: "la tortue luth",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fc/Leatherback_sea_turtle_Tinglar%2C_USVI_%285839996547%29.jpg/330px-Leatherback_sea_turtle_Tinglar%2C_USVI_%285839996547%29.jpg",
    credit: { author: "U.S. Fish and Wildlife Service Southeast Region", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Leatherback_sea_turtle_Tinglar,_USVI_(5839996547).jpg" } },
  { id: "salamandre", name: "Salamandre", the: "la salamandre",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1b/Salamandra_salamandra_MHNT_1.jpg/330px-Salamandra_salamandra_MHNT_1.jpg",
    credit: { author: "Didier Descouens", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Salamandra_salamandra_MHNT_1.jpg" } },
  { id: "dendrobate", name: "Dendrobate", the: "le dendrobate",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Dendrobates_tinctorius_-_Karlsruhe_Zoo_05.jpg/330px-Dendrobates_tinctorius_-_Karlsruhe_Zoo_05.jpg",
    credit: { author: "H. Zell", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Dendrobates_tinctorius_-_Karlsruhe_Zoo_05.jpg" } },
  { id: "binturong", name: "Binturong", the: "le binturong",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Binturong_in_Overloon.jpg/330px-Binturong_in_Overloon.jpg",
    credit: { author: "Tassilo Rau", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Binturong_in_Overloon.jpg" } },
  { id: "orycterope", name: "Oryctérope", the: "l'oryctérope",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Orycteropus_afer_175359469.jpg/330px-Orycteropus_afer_175359469.jpg",
    credit: { author: "Kelly Abram", license: "CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:Orycteropus_afer_175359469.jpg" } },
  { id: "saiga", name: "Saïga", the: "le saïga",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Saiga_antelope_at_the_Stepnoi_Sanctuary.jpg/330px-Saiga_antelope_at_the_Stepnoi_Sanctuary.jpg",
    credit: { author: "Andrey Giljov", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Saiga_antelope_at_the_Stepnoi_Sanctuary.jpg" } },
  { id: "mandrill", name: "Mandrill", the: "le mandrill",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ed/Mandrill_Albert_September_2015_Zoo_Berlin_%282%29.jpg/330px-Mandrill_Albert_September_2015_Zoo_Berlin_%282%29.jpg",
    credit: { author: "Katma0601", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Mandrill_Albert_September_2015_Zoo_Berlin_(2).jpg" } },
  { id: "babiroussa", name: "Babiroussa", the: "le babiroussa",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/Hirscheber1a.jpg/330px-Hirscheber1a.jpg",
    credit: { author: "Masteraah at German Wikipedia", license: "CC BY-SA 2.0 de", page: "https://commons.wikimedia.org/wiki/File:Hirscheber1a.jpg" } },
  { id: "oursalunettes", name: "Ours à lunettes", the: "l'ours à lunettes",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Tremarctos_ornatus_in_Jardim_Zool%C3%B3gico_de_Curitiba.jpg/330px-Tremarctos_ornatus_in_Jardim_Zool%C3%B3gico_de_Curitiba.jpg",
    credit: { author: "Wilfredor", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Tremarctos_ornatus_in_Jardim_Zool%C3%B3gico_de_Curitiba.jpg" } },
  { id: "loupacriniere", name: "Loup à crinière", the: "le loup à crinière",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Lobo_Guar%C3%A1_andando.jpg/330px-Lobo_Guar%C3%A1_andando.jpg",
    credit: { author: "Jonathan Wilkins", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Lobo_Guar%C3%A1_andando.jpg" } },
  { id: "serpentaire", name: "Serpentaire", the: "le serpentaire",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Secretary_bird_Mara_for_WC.jpg/330px-Secretary_bird_Mara_for_WC.jpg",
    credit: { author: "Sumeet Moghe", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Secretary_bird_Mara_for_WC.jpg" } },
  { id: "kakapo", name: "Kakapo", the: "le kakapo",
    photo: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Sirocco_full_length_portrait.jpg/330px-Sirocco_full_length_portrait.jpg",
    credit: { author: "Department of Conservation", license: "CC BY 2.0", page: "https://commons.wikimedia.org/wiki/File:Sirocco_full_length_portrait.jpg" } },
];
