// ============================================================================
// Les 64 animaux du quiz.
//
// Les dessins viennent de "Noto Emoji" de Google (licence Apache 2.0),
// servis par les serveurs de Google Fonts. Chaque image est nommée d'après le
// code Unicode de l'émoji correspondant (séquences séparées par "_").
// ============================================================================

const IMAGE_BASE = "https://fonts.gstatic.com/s/e/notoemoji/latest/";

export const imageUrl = (animal) => `${IMAGE_BASE}${animal.img}/emoji.svg`;

// "the" = le nom avec son article, pour la question "Où est… ?"
export const ANIMALS = [
  { id: "chien",        name: "Chien",         the: "le chien",         img: "1f415" },
  { id: "chat",         name: "Chat",          the: "le chat",          img: "1f408" },
  { id: "cheval",       name: "Cheval",        the: "le cheval",        img: "1f40e" },
  { id: "vache",        name: "Vache",         the: "la vache",         img: "1f404" },
  { id: "cochon",       name: "Cochon",        the: "le cochon",        img: "1f416" },
  { id: "mouton",       name: "Mouton",        the: "le mouton",        img: "1f411" },
  { id: "chevre",       name: "Chèvre",        the: "la chèvre",        img: "1f410" },
  { id: "poule",        name: "Poule",         the: "la poule",         img: "1f414" },
  { id: "canard",       name: "Canard",        the: "le canard",        img: "1f986" },
  { id: "lapin",        name: "Lapin",         the: "le lapin",         img: "1f407" },
  { id: "souris",       name: "Souris",        the: "la souris",        img: "1f401" },
  { id: "ecureuil",     name: "Écureuil",      the: "l'écureuil",       img: "1f43f" },
  { id: "herisson",     name: "Hérisson",      the: "le hérisson",      img: "1f994" },
  { id: "chauvesouris", name: "Chauve-souris", the: "la chauve-souris", img: "1f987" },
  { id: "hibou",        name: "Hibou",         the: "le hibou",         img: "1f989" },
  { id: "aigle",        name: "Aigle",         the: "l'aigle",          img: "1f985" },
  { id: "perroquet",    name: "Perroquet",     the: "le perroquet",     img: "1f99c" },
  { id: "paon",         name: "Paon",          the: "le paon",          img: "1f99a" },
  { id: "flamant",      name: "Flamant rose",  the: "le flamant rose",  img: "1f9a9" },
  { id: "manchot",      name: "Manchot",       the: "le manchot",       img: "1f427" },
  { id: "cygne",        name: "Cygne",         the: "le cygne",         img: "1f9a2" },
  { id: "dinde",        name: "Dinde",         the: "la dinde",         img: "1f983" },
  { id: "elephant",     name: "Éléphant",      the: "l'éléphant",       img: "1f418" },
  { id: "girafe",       name: "Girafe",        the: "la girafe",        img: "1f992" },
  { id: "zebre",        name: "Zèbre",         the: "le zèbre",         img: "1f993" },
  { id: "rhinoceros",   name: "Rhinocéros",    the: "le rhinocéros",    img: "1f98f" },
  { id: "hippopotame",  name: "Hippopotame",   the: "l'hippopotame",    img: "1f99b" },
  { id: "chameau",      name: "Chameau",       the: "le chameau",       img: "1f42b" },
  { id: "kangourou",    name: "Kangourou",     the: "le kangourou",     img: "1f998" },
  { id: "gorille",      name: "Gorille",       the: "le gorille",       img: "1f98d" },
  { id: "orangoutan",   name: "Orang-outan",   the: "l'orang-outan",    img: "1f9a7" },
  { id: "lion",         name: "Lion",          the: "le lion",          img: "1f981" },
  { id: "tigre",        name: "Tigre",         the: "le tigre",         img: "1f405" },
  { id: "leopard",      name: "Léopard",       the: "le léopard",       img: "1f406" },
  { id: "ours",         name: "Ours",          the: "l'ours",           img: "1f43b" },
  { id: "ourspolaire",  name: "Ours polaire",  the: "l'ours polaire",   img: "1f43b_200d_2744_fe0f" },
  { id: "panda",        name: "Panda",         the: "le panda",         img: "1f43c" },
  { id: "koala",        name: "Koala",         the: "le koala",         img: "1f428" },
  { id: "renard",       name: "Renard",        the: "le renard",        img: "1f98a" },
  { id: "loup",         name: "Loup",          the: "le loup",          img: "1f43a" },
  { id: "raton",        name: "Raton laveur",  the: "le raton laveur",  img: "1f99d" },
  { id: "loutre",       name: "Loutre",        the: "la loutre",        img: "1f9a6" },
  { id: "paresseux",    name: "Paresseux",     the: "le paresseux",     img: "1f9a5" },
  { id: "mouffette",    name: "Mouffette",     the: "la mouffette",     img: "1f9a8" },
  { id: "castor",       name: "Castor",        the: "le castor",        img: "1f9ab" },
  { id: "cerf",         name: "Cerf",          the: "le cerf",          img: "1f98c" },
  { id: "bison",        name: "Bison",         the: "le bison",         img: "1f9ac" },
  { id: "lama",         name: "Lama",          the: "le lama",          img: "1f999" },
  { id: "crocodile",    name: "Crocodile",     the: "le crocodile",     img: "1f40a" },
  { id: "tortue",       name: "Tortue",        the: "la tortue",        img: "1f422" },
  { id: "lezard",       name: "Lézard",        the: "le lézard",        img: "1f98e" },
  { id: "serpent",      name: "Serpent",       the: "le serpent",       img: "1f40d" },
  { id: "grenouille",   name: "Grenouille",    the: "la grenouille",    img: "1f438" },
  { id: "dauphin",      name: "Dauphin",       the: "le dauphin",       img: "1f42c" },
  { id: "baleine",      name: "Baleine",       the: "la baleine",       img: "1f433" },
  { id: "requin",       name: "Requin",        the: "le requin",        img: "1f988" },
  { id: "pieuvre",      name: "Pieuvre",       the: "la pieuvre",       img: "1f419" },
  { id: "crabe",        name: "Crabe",         the: "le crabe",         img: "1f980" },
  { id: "poissonglobe", name: "Poisson-globe", the: "le poisson-globe", img: "1f421" },
  { id: "phoque",       name: "Phoque",        the: "le phoque",        img: "1f9ad" },
  { id: "escargot",     name: "Escargot",      the: "l'escargot",       img: "1f40c" },
  { id: "papillon",     name: "Papillon",      the: "le papillon",      img: "1f98b" },
  { id: "abeille",      name: "Abeille",       the: "l'abeille",        img: "1f41d" },
  { id: "coccinelle",   name: "Coccinelle",    the: "la coccinelle",    img: "1f41e" },
];
